/*
Omnistrate Registration API

REST API for Omnistrate Service Registration

API version: 2022-09-01-00
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
	"fmt"
)

// checks if the SetEnvironmentVariablesRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetEnvironmentVariablesRequest{}

// SetEnvironmentVariablesRequest struct for SetEnvironmentVariablesRequest
type SetEnvironmentVariablesRequest struct {
	// The environment variables that this resource requires
	EnvironmentVariables []EnvironmentVariable `json:"environmentVariables,omitempty"`
	// ID of a resource
	Id string `json:"id"`
	// ID of a Service
	ServiceId string `json:"serviceId"`
	// JWT token used to perform authorization
	Token string `json:"token"`
	AdditionalProperties map[string]interface{}
}

type _SetEnvironmentVariablesRequest SetEnvironmentVariablesRequest

// NewSetEnvironmentVariablesRequest instantiates a new SetEnvironmentVariablesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetEnvironmentVariablesRequest(id string, serviceId string, token string) *SetEnvironmentVariablesRequest {
	this := SetEnvironmentVariablesRequest{}
	this.Id = id
	this.ServiceId = serviceId
	this.Token = token
	return &this
}

// NewSetEnvironmentVariablesRequestWithDefaults instantiates a new SetEnvironmentVariablesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetEnvironmentVariablesRequestWithDefaults() *SetEnvironmentVariablesRequest {
	this := SetEnvironmentVariablesRequest{}
	return &this
}

// GetEnvironmentVariables returns the EnvironmentVariables field value if set, zero value otherwise.
func (o *SetEnvironmentVariablesRequest) GetEnvironmentVariables() []EnvironmentVariable {
	if o == nil || IsNil(o.EnvironmentVariables) {
		var ret []EnvironmentVariable
		return ret
	}
	return o.EnvironmentVariables
}

// GetEnvironmentVariablesOk returns a tuple with the EnvironmentVariables field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SetEnvironmentVariablesRequest) GetEnvironmentVariablesOk() ([]EnvironmentVariable, bool) {
	if o == nil || IsNil(o.EnvironmentVariables) {
		return nil, false
	}
	return o.EnvironmentVariables, true
}

// SetEnvironmentVariables gets a reference to the given []EnvironmentVariable and assigns it to the EnvironmentVariables field.
func (o *SetEnvironmentVariablesRequest) SetEnvironmentVariables(v []EnvironmentVariable) {
	o.EnvironmentVariables = v
}

// GetId returns the Id field value
func (o *SetEnvironmentVariablesRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SetEnvironmentVariablesRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SetEnvironmentVariablesRequest) SetId(v string) {
	o.Id = v
}

// GetServiceId returns the ServiceId field value
func (o *SetEnvironmentVariablesRequest) GetServiceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ServiceId
}

// GetServiceIdOk returns a tuple with the ServiceId field value
// and a boolean to check if the value has been set.
func (o *SetEnvironmentVariablesRequest) GetServiceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceId, true
}

// SetServiceId sets field value
func (o *SetEnvironmentVariablesRequest) SetServiceId(v string) {
	o.ServiceId = v
}

// GetToken returns the Token field value
func (o *SetEnvironmentVariablesRequest) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *SetEnvironmentVariablesRequest) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *SetEnvironmentVariablesRequest) SetToken(v string) {
	o.Token = v
}

func (o SetEnvironmentVariablesRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetEnvironmentVariablesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EnvironmentVariables) {
		toSerialize["environmentVariables"] = o.EnvironmentVariables
	}
	toSerialize["id"] = o.Id
	toSerialize["serviceId"] = o.ServiceId
	toSerialize["token"] = o.Token

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SetEnvironmentVariablesRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"serviceId",
		"token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSetEnvironmentVariablesRequest := _SetEnvironmentVariablesRequest{}

	err = json.Unmarshal(data, &varSetEnvironmentVariablesRequest)

	if err != nil {
		return err
	}

	*o = SetEnvironmentVariablesRequest(varSetEnvironmentVariablesRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "environmentVariables")
		delete(additionalProperties, "id")
		delete(additionalProperties, "serviceId")
		delete(additionalProperties, "token")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSetEnvironmentVariablesRequest struct {
	value *SetEnvironmentVariablesRequest
	isSet bool
}

func (v NullableSetEnvironmentVariablesRequest) Get() *SetEnvironmentVariablesRequest {
	return v.value
}

func (v *NullableSetEnvironmentVariablesRequest) Set(val *SetEnvironmentVariablesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSetEnvironmentVariablesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSetEnvironmentVariablesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetEnvironmentVariablesRequest(val *SetEnvironmentVariablesRequest) *NullableSetEnvironmentVariablesRequest {
	return &NullableSetEnvironmentVariablesRequest{value: val, isSet: true}
}

func (v NullableSetEnvironmentVariablesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetEnvironmentVariablesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

