/*
Omnistrate Registration API

REST API for Omnistrate Service Registration

API version: 2022-09-01-00
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
	"fmt"
)

// checks if the ListNetworkConfigsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListNetworkConfigsRequest{}

// ListNetworkConfigsRequest struct for ListNetworkConfigsRequest
type ListNetworkConfigsRequest struct {
	// Is network config managed by omnistrate
	Managed *bool `json:"managed,omitempty"`
	// ID of a Service
	ServiceId string `json:"serviceId"`
	// JWT token used to perform authorization
	Token string `json:"token"`
	AdditionalProperties map[string]interface{}
}

type _ListNetworkConfigsRequest ListNetworkConfigsRequest

// NewListNetworkConfigsRequest instantiates a new ListNetworkConfigsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListNetworkConfigsRequest(serviceId string, token string) *ListNetworkConfigsRequest {
	this := ListNetworkConfigsRequest{}
	this.ServiceId = serviceId
	this.Token = token
	return &this
}

// NewListNetworkConfigsRequestWithDefaults instantiates a new ListNetworkConfigsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListNetworkConfigsRequestWithDefaults() *ListNetworkConfigsRequest {
	this := ListNetworkConfigsRequest{}
	return &this
}

// GetManaged returns the Managed field value if set, zero value otherwise.
func (o *ListNetworkConfigsRequest) GetManaged() bool {
	if o == nil || IsNil(o.Managed) {
		var ret bool
		return ret
	}
	return *o.Managed
}

// GetManagedOk returns a tuple with the Managed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListNetworkConfigsRequest) GetManagedOk() (*bool, bool) {
	if o == nil || IsNil(o.Managed) {
		return nil, false
	}
	return o.Managed, true
}

// SetManaged gets a reference to the given bool and assigns it to the Managed field.
func (o *ListNetworkConfigsRequest) SetManaged(v bool) {
	o.Managed = &v
}

// GetServiceId returns the ServiceId field value
func (o *ListNetworkConfigsRequest) GetServiceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ServiceId
}

// GetServiceIdOk returns a tuple with the ServiceId field value
// and a boolean to check if the value has been set.
func (o *ListNetworkConfigsRequest) GetServiceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceId, true
}

// SetServiceId sets field value
func (o *ListNetworkConfigsRequest) SetServiceId(v string) {
	o.ServiceId = v
}

// GetToken returns the Token field value
func (o *ListNetworkConfigsRequest) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *ListNetworkConfigsRequest) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *ListNetworkConfigsRequest) SetToken(v string) {
	o.Token = v
}

func (o ListNetworkConfigsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListNetworkConfigsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Managed) {
		toSerialize["managed"] = o.Managed
	}
	toSerialize["serviceId"] = o.ServiceId
	toSerialize["token"] = o.Token

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListNetworkConfigsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"serviceId",
		"token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListNetworkConfigsRequest := _ListNetworkConfigsRequest{}

	err = json.Unmarshal(data, &varListNetworkConfigsRequest)

	if err != nil {
		return err
	}

	*o = ListNetworkConfigsRequest(varListNetworkConfigsRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "managed")
		delete(additionalProperties, "serviceId")
		delete(additionalProperties, "token")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListNetworkConfigsRequest struct {
	value *ListNetworkConfigsRequest
	isSet bool
}

func (v NullableListNetworkConfigsRequest) Get() *ListNetworkConfigsRequest {
	return v.value
}

func (v *NullableListNetworkConfigsRequest) Set(val *ListNetworkConfigsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableListNetworkConfigsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableListNetworkConfigsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListNetworkConfigsRequest(val *ListNetworkConfigsRequest) *NullableListNetworkConfigsRequest {
	return &NullableListNetworkConfigsRequest{value: val, isSet: true}
}

func (v NullableListNetworkConfigsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListNetworkConfigsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

