/*
Omnistrate Registration API

REST API for Omnistrate Service Registration

API version: 2022-09-01-00
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
	"fmt"
)

// checks if the SetSecretRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetSecretRequest{}

// SetSecretRequest struct for SetSecretRequest
type SetSecretRequest struct {
	// The type of service environment
	EnvironmentType string `json:"environmentType"`
	// Name of the secret
	Name string `json:"name"`
	// JWT token used to perform authorization
	Token string `json:"token"`
	// The value of the secret
	Value string `json:"value"`
	AdditionalProperties map[string]interface{}
}

type _SetSecretRequest SetSecretRequest

// NewSetSecretRequest instantiates a new SetSecretRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetSecretRequest(environmentType string, name string, token string, value string) *SetSecretRequest {
	this := SetSecretRequest{}
	this.EnvironmentType = environmentType
	this.Name = name
	this.Token = token
	this.Value = value
	return &this
}

// NewSetSecretRequestWithDefaults instantiates a new SetSecretRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetSecretRequestWithDefaults() *SetSecretRequest {
	this := SetSecretRequest{}
	return &this
}

// GetEnvironmentType returns the EnvironmentType field value
func (o *SetSecretRequest) GetEnvironmentType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EnvironmentType
}

// GetEnvironmentTypeOk returns a tuple with the EnvironmentType field value
// and a boolean to check if the value has been set.
func (o *SetSecretRequest) GetEnvironmentTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EnvironmentType, true
}

// SetEnvironmentType sets field value
func (o *SetSecretRequest) SetEnvironmentType(v string) {
	o.EnvironmentType = v
}

// GetName returns the Name field value
func (o *SetSecretRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SetSecretRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SetSecretRequest) SetName(v string) {
	o.Name = v
}

// GetToken returns the Token field value
func (o *SetSecretRequest) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *SetSecretRequest) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *SetSecretRequest) SetToken(v string) {
	o.Token = v
}

// GetValue returns the Value field value
func (o *SetSecretRequest) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *SetSecretRequest) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *SetSecretRequest) SetValue(v string) {
	o.Value = v
}

func (o SetSecretRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetSecretRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["environmentType"] = o.EnvironmentType
	toSerialize["name"] = o.Name
	toSerialize["token"] = o.Token
	toSerialize["value"] = o.Value

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SetSecretRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"environmentType",
		"name",
		"token",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSetSecretRequest := _SetSecretRequest{}

	err = json.Unmarshal(data, &varSetSecretRequest)

	if err != nil {
		return err
	}

	*o = SetSecretRequest(varSetSecretRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "environmentType")
		delete(additionalProperties, "name")
		delete(additionalProperties, "token")
		delete(additionalProperties, "value")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSetSecretRequest struct {
	value *SetSecretRequest
	isSet bool
}

func (v NullableSetSecretRequest) Get() *SetSecretRequest {
	return v.value
}

func (v *NullableSetSecretRequest) Set(val *SetSecretRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSetSecretRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSetSecretRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetSecretRequest(val *SetSecretRequest) *NullableSetSecretRequest {
	return &NullableSetSecretRequest{value: val, isSet: true}
}

func (v NullableSetSecretRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetSecretRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


