/*
Omnistrate Registration API

REST API for Omnistrate Service Registration

API version: 2022-09-01-00
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// checks if the UpdateOutputParameterRequest2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateOutputParameterRequest2{}

// UpdateOutputParameterRequest2 struct for UpdateOutputParameterRequest2
type UpdateOutputParameterRequest2 struct {
	// Description of the output variable being exported
	Description *string `json:"description,omitempty"`
	GenericCommandValueProvider *GenericCommandValueProviderConfig `json:"genericCommandValueProvider,omitempty"`
	KubectlValueProvider *KubectlValueProviderConfig `json:"kubectlValueProvider,omitempty"`
	// External name of the output variable being exported
	Name *string `json:"name,omitempty"`
	// Value of the output variable being exported
	Value *string `json:"value,omitempty"`
	// Reference to an input variable that will be used to set the value of the output variable being exported
	ValueRef *string `json:"valueRef,omitempty"`
	ValueType *string `json:"valueType,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UpdateOutputParameterRequest2 UpdateOutputParameterRequest2

// NewUpdateOutputParameterRequest2 instantiates a new UpdateOutputParameterRequest2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateOutputParameterRequest2() *UpdateOutputParameterRequest2 {
	this := UpdateOutputParameterRequest2{}
	return &this
}

// NewUpdateOutputParameterRequest2WithDefaults instantiates a new UpdateOutputParameterRequest2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateOutputParameterRequest2WithDefaults() *UpdateOutputParameterRequest2 {
	this := UpdateOutputParameterRequest2{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *UpdateOutputParameterRequest2) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOutputParameterRequest2) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *UpdateOutputParameterRequest2) SetDescription(v string) {
	o.Description = &v
}

// GetGenericCommandValueProvider returns the GenericCommandValueProvider field value if set, zero value otherwise.
func (o *UpdateOutputParameterRequest2) GetGenericCommandValueProvider() GenericCommandValueProviderConfig {
	if o == nil || IsNil(o.GenericCommandValueProvider) {
		var ret GenericCommandValueProviderConfig
		return ret
	}
	return *o.GenericCommandValueProvider
}

// GetGenericCommandValueProviderOk returns a tuple with the GenericCommandValueProvider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOutputParameterRequest2) GetGenericCommandValueProviderOk() (*GenericCommandValueProviderConfig, bool) {
	if o == nil || IsNil(o.GenericCommandValueProvider) {
		return nil, false
	}
	return o.GenericCommandValueProvider, true
}

// SetGenericCommandValueProvider gets a reference to the given GenericCommandValueProviderConfig and assigns it to the GenericCommandValueProvider field.
func (o *UpdateOutputParameterRequest2) SetGenericCommandValueProvider(v GenericCommandValueProviderConfig) {
	o.GenericCommandValueProvider = &v
}

// GetKubectlValueProvider returns the KubectlValueProvider field value if set, zero value otherwise.
func (o *UpdateOutputParameterRequest2) GetKubectlValueProvider() KubectlValueProviderConfig {
	if o == nil || IsNil(o.KubectlValueProvider) {
		var ret KubectlValueProviderConfig
		return ret
	}
	return *o.KubectlValueProvider
}

// GetKubectlValueProviderOk returns a tuple with the KubectlValueProvider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOutputParameterRequest2) GetKubectlValueProviderOk() (*KubectlValueProviderConfig, bool) {
	if o == nil || IsNil(o.KubectlValueProvider) {
		return nil, false
	}
	return o.KubectlValueProvider, true
}

// SetKubectlValueProvider gets a reference to the given KubectlValueProviderConfig and assigns it to the KubectlValueProvider field.
func (o *UpdateOutputParameterRequest2) SetKubectlValueProvider(v KubectlValueProviderConfig) {
	o.KubectlValueProvider = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateOutputParameterRequest2) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOutputParameterRequest2) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateOutputParameterRequest2) SetName(v string) {
	o.Name = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *UpdateOutputParameterRequest2) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOutputParameterRequest2) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *UpdateOutputParameterRequest2) SetValue(v string) {
	o.Value = &v
}

// GetValueRef returns the ValueRef field value if set, zero value otherwise.
func (o *UpdateOutputParameterRequest2) GetValueRef() string {
	if o == nil || IsNil(o.ValueRef) {
		var ret string
		return ret
	}
	return *o.ValueRef
}

// GetValueRefOk returns a tuple with the ValueRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOutputParameterRequest2) GetValueRefOk() (*string, bool) {
	if o == nil || IsNil(o.ValueRef) {
		return nil, false
	}
	return o.ValueRef, true
}

// SetValueRef gets a reference to the given string and assigns it to the ValueRef field.
func (o *UpdateOutputParameterRequest2) SetValueRef(v string) {
	o.ValueRef = &v
}

// GetValueType returns the ValueType field value if set, zero value otherwise.
func (o *UpdateOutputParameterRequest2) GetValueType() string {
	if o == nil || IsNil(o.ValueType) {
		var ret string
		return ret
	}
	return *o.ValueType
}

// GetValueTypeOk returns a tuple with the ValueType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOutputParameterRequest2) GetValueTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ValueType) {
		return nil, false
	}
	return o.ValueType, true
}

// SetValueType gets a reference to the given string and assigns it to the ValueType field.
func (o *UpdateOutputParameterRequest2) SetValueType(v string) {
	o.ValueType = &v
}

func (o UpdateOutputParameterRequest2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateOutputParameterRequest2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.GenericCommandValueProvider) {
		toSerialize["genericCommandValueProvider"] = o.GenericCommandValueProvider
	}
	if !IsNil(o.KubectlValueProvider) {
		toSerialize["kubectlValueProvider"] = o.KubectlValueProvider
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	if !IsNil(o.ValueRef) {
		toSerialize["valueRef"] = o.ValueRef
	}
	if !IsNil(o.ValueType) {
		toSerialize["valueType"] = o.ValueType
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateOutputParameterRequest2) UnmarshalJSON(data []byte) (err error) {
	varUpdateOutputParameterRequest2 := _UpdateOutputParameterRequest2{}

	err = json.Unmarshal(data, &varUpdateOutputParameterRequest2)

	if err != nil {
		return err
	}

	*o = UpdateOutputParameterRequest2(varUpdateOutputParameterRequest2)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "description")
		delete(additionalProperties, "genericCommandValueProvider")
		delete(additionalProperties, "kubectlValueProvider")
		delete(additionalProperties, "name")
		delete(additionalProperties, "value")
		delete(additionalProperties, "valueRef")
		delete(additionalProperties, "valueType")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateOutputParameterRequest2 struct {
	value *UpdateOutputParameterRequest2
	isSet bool
}

func (v NullableUpdateOutputParameterRequest2) Get() *UpdateOutputParameterRequest2 {
	return v.value
}

func (v *NullableUpdateOutputParameterRequest2) Set(val *UpdateOutputParameterRequest2) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateOutputParameterRequest2) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateOutputParameterRequest2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateOutputParameterRequest2(val *UpdateOutputParameterRequest2) *NullableUpdateOutputParameterRequest2 {
	return &NullableUpdateOutputParameterRequest2{value: val, isSet: true}
}

func (v NullableUpdateOutputParameterRequest2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateOutputParameterRequest2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


