/*
Omnistrate Registration API

REST API for Omnistrate Service Registration

API version: 2022-09-01-00
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// checks if the AddResourceDependencyRequest2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddResourceDependencyRequest2{}

// AddResourceDependencyRequest2 struct for AddResourceDependencyRequest2
type AddResourceDependencyRequest2 struct {
	// A map of the source parameter to the dependency resource parameter
	ParameterMap *map[string]string `json:"parameterMap,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AddResourceDependencyRequest2 AddResourceDependencyRequest2

// NewAddResourceDependencyRequest2 instantiates a new AddResourceDependencyRequest2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddResourceDependencyRequest2() *AddResourceDependencyRequest2 {
	this := AddResourceDependencyRequest2{}
	return &this
}

// NewAddResourceDependencyRequest2WithDefaults instantiates a new AddResourceDependencyRequest2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddResourceDependencyRequest2WithDefaults() *AddResourceDependencyRequest2 {
	this := AddResourceDependencyRequest2{}
	return &this
}

// GetParameterMap returns the ParameterMap field value if set, zero value otherwise.
func (o *AddResourceDependencyRequest2) GetParameterMap() map[string]string {
	if o == nil || IsNil(o.ParameterMap) {
		var ret map[string]string
		return ret
	}
	return *o.ParameterMap
}

// GetParameterMapOk returns a tuple with the ParameterMap field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddResourceDependencyRequest2) GetParameterMapOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.ParameterMap) {
		return nil, false
	}
	return o.ParameterMap, true
}

// SetParameterMap gets a reference to the given map[string]string and assigns it to the ParameterMap field.
func (o *AddResourceDependencyRequest2) SetParameterMap(v map[string]string) {
	o.ParameterMap = &v
}

func (o AddResourceDependencyRequest2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddResourceDependencyRequest2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ParameterMap) {
		toSerialize["parameterMap"] = o.ParameterMap
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AddResourceDependencyRequest2) UnmarshalJSON(data []byte) (err error) {
	varAddResourceDependencyRequest2 := _AddResourceDependencyRequest2{}

	err = json.Unmarshal(data, &varAddResourceDependencyRequest2)

	if err != nil {
		return err
	}

	*o = AddResourceDependencyRequest2(varAddResourceDependencyRequest2)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "parameterMap")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAddResourceDependencyRequest2 struct {
	value *AddResourceDependencyRequest2
	isSet bool
}

func (v NullableAddResourceDependencyRequest2) Get() *AddResourceDependencyRequest2 {
	return v.value
}

func (v *NullableAddResourceDependencyRequest2) Set(val *AddResourceDependencyRequest2) {
	v.value = val
	v.isSet = true
}

func (v NullableAddResourceDependencyRequest2) IsSet() bool {
	return v.isSet
}

func (v *NullableAddResourceDependencyRequest2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddResourceDependencyRequest2(val *AddResourceDependencyRequest2) *NullableAddResourceDependencyRequest2 {
	return &NullableAddResourceDependencyRequest2{value: val, isSet: true}
}

func (v NullableAddResourceDependencyRequest2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddResourceDependencyRequest2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


