/*
Omnistrate Registration API

REST API for Omnistrate Service Registration

API version: 2022-09-01-00
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// checks if the DescribeDeploymentArtifactRequest2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DescribeDeploymentArtifactRequest2{}

// DescribeDeploymentArtifactRequest2 struct for DescribeDeploymentArtifactRequest2
type DescribeDeploymentArtifactRequest2 struct {
	// The hash of the deployment artifact to be described. It is used as an additional filter criteria to ensure the id and the hash match for the same deployment artifact.
	Hash *string `json:"hash,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DescribeDeploymentArtifactRequest2 DescribeDeploymentArtifactRequest2

// NewDescribeDeploymentArtifactRequest2 instantiates a new DescribeDeploymentArtifactRequest2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDescribeDeploymentArtifactRequest2() *DescribeDeploymentArtifactRequest2 {
	this := DescribeDeploymentArtifactRequest2{}
	return &this
}

// NewDescribeDeploymentArtifactRequest2WithDefaults instantiates a new DescribeDeploymentArtifactRequest2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDescribeDeploymentArtifactRequest2WithDefaults() *DescribeDeploymentArtifactRequest2 {
	this := DescribeDeploymentArtifactRequest2{}
	return &this
}

// GetHash returns the Hash field value if set, zero value otherwise.
func (o *DescribeDeploymentArtifactRequest2) GetHash() string {
	if o == nil || IsNil(o.Hash) {
		var ret string
		return ret
	}
	return *o.Hash
}

// GetHashOk returns a tuple with the Hash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DescribeDeploymentArtifactRequest2) GetHashOk() (*string, bool) {
	if o == nil || IsNil(o.Hash) {
		return nil, false
	}
	return o.Hash, true
}

// SetHash gets a reference to the given string and assigns it to the Hash field.
func (o *DescribeDeploymentArtifactRequest2) SetHash(v string) {
	o.Hash = &v
}

func (o DescribeDeploymentArtifactRequest2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DescribeDeploymentArtifactRequest2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Hash) {
		toSerialize["hash"] = o.Hash
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DescribeDeploymentArtifactRequest2) UnmarshalJSON(data []byte) (err error) {
	varDescribeDeploymentArtifactRequest2 := _DescribeDeploymentArtifactRequest2{}

	err = json.Unmarshal(data, &varDescribeDeploymentArtifactRequest2)

	if err != nil {
		return err
	}

	*o = DescribeDeploymentArtifactRequest2(varDescribeDeploymentArtifactRequest2)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "hash")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDescribeDeploymentArtifactRequest2 struct {
	value *DescribeDeploymentArtifactRequest2
	isSet bool
}

func (v NullableDescribeDeploymentArtifactRequest2) Get() *DescribeDeploymentArtifactRequest2 {
	return v.value
}

func (v *NullableDescribeDeploymentArtifactRequest2) Set(val *DescribeDeploymentArtifactRequest2) {
	v.value = val
	v.isSet = true
}

func (v NullableDescribeDeploymentArtifactRequest2) IsSet() bool {
	return v.isSet
}

func (v *NullableDescribeDeploymentArtifactRequest2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDescribeDeploymentArtifactRequest2(val *DescribeDeploymentArtifactRequest2) *NullableDescribeDeploymentArtifactRequest2 {
	return &NullableDescribeDeploymentArtifactRequest2{value: val, isSet: true}
}

func (v NullableDescribeDeploymentArtifactRequest2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDescribeDeploymentArtifactRequest2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

