/*
Omnistrate Registration API

REST API for Omnistrate Service Registration

API version: 2022-09-01-00
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// checks if the UpdateNetworkConfigRequest2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateNetworkConfigRequest2{}

// UpdateNetworkConfigRequest2 struct for UpdateNetworkConfigRequest2
type UpdateNetworkConfigRequest2 struct {
	// A brief description of the network config
	Description *string `json:"description,omitempty"`
	// Generates a DNS endpoint per-replica for this network config
	EndpointPerReplica *bool `json:"endpointPerReplica,omitempty"`
	// Restrict access to this network config to the internal network
	Internal *bool `json:"internal,omitempty"`
	// Name of the network config
	Name *string `json:"name,omitempty"`
	// Ports to map to the generated DNS endpoint
	OpenPorts []int64 `json:"openPorts,omitempty"`
	PrivateNetworkingConfiguration *PrivateNetworkingConfiguration `json:"privateNetworkingConfiguration,omitempty"`
	PublicNetworkingConfiguration *PublicNetworkingConfiguration `json:"publicNetworkingConfiguration,omitempty"`
	// Create an external node load balancer per node rather than expose the node ip directly
	StableEgressIP *bool `json:"stableEgressIP,omitempty"`
	// The port that hosts the reverse proxy for TLS termination
	TlsTerminationPort *int64 `json:"tlsTerminationPort,omitempty"`
	// The preferred type of zonal availability for this resource and the specific zone(s) to deploy in
	ZoneConfiguration *string `json:"zoneConfiguration,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UpdateNetworkConfigRequest2 UpdateNetworkConfigRequest2

// NewUpdateNetworkConfigRequest2 instantiates a new UpdateNetworkConfigRequest2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateNetworkConfigRequest2() *UpdateNetworkConfigRequest2 {
	this := UpdateNetworkConfigRequest2{}
	return &this
}

// NewUpdateNetworkConfigRequest2WithDefaults instantiates a new UpdateNetworkConfigRequest2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateNetworkConfigRequest2WithDefaults() *UpdateNetworkConfigRequest2 {
	this := UpdateNetworkConfigRequest2{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *UpdateNetworkConfigRequest2) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNetworkConfigRequest2) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *UpdateNetworkConfigRequest2) SetDescription(v string) {
	o.Description = &v
}

// GetEndpointPerReplica returns the EndpointPerReplica field value if set, zero value otherwise.
func (o *UpdateNetworkConfigRequest2) GetEndpointPerReplica() bool {
	if o == nil || IsNil(o.EndpointPerReplica) {
		var ret bool
		return ret
	}
	return *o.EndpointPerReplica
}

// GetEndpointPerReplicaOk returns a tuple with the EndpointPerReplica field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNetworkConfigRequest2) GetEndpointPerReplicaOk() (*bool, bool) {
	if o == nil || IsNil(o.EndpointPerReplica) {
		return nil, false
	}
	return o.EndpointPerReplica, true
}

// SetEndpointPerReplica gets a reference to the given bool and assigns it to the EndpointPerReplica field.
func (o *UpdateNetworkConfigRequest2) SetEndpointPerReplica(v bool) {
	o.EndpointPerReplica = &v
}

// GetInternal returns the Internal field value if set, zero value otherwise.
func (o *UpdateNetworkConfigRequest2) GetInternal() bool {
	if o == nil || IsNil(o.Internal) {
		var ret bool
		return ret
	}
	return *o.Internal
}

// GetInternalOk returns a tuple with the Internal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNetworkConfigRequest2) GetInternalOk() (*bool, bool) {
	if o == nil || IsNil(o.Internal) {
		return nil, false
	}
	return o.Internal, true
}

// SetInternal gets a reference to the given bool and assigns it to the Internal field.
func (o *UpdateNetworkConfigRequest2) SetInternal(v bool) {
	o.Internal = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateNetworkConfigRequest2) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNetworkConfigRequest2) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateNetworkConfigRequest2) SetName(v string) {
	o.Name = &v
}

// GetOpenPorts returns the OpenPorts field value if set, zero value otherwise.
func (o *UpdateNetworkConfigRequest2) GetOpenPorts() []int64 {
	if o == nil || IsNil(o.OpenPorts) {
		var ret []int64
		return ret
	}
	return o.OpenPorts
}

// GetOpenPortsOk returns a tuple with the OpenPorts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNetworkConfigRequest2) GetOpenPortsOk() ([]int64, bool) {
	if o == nil || IsNil(o.OpenPorts) {
		return nil, false
	}
	return o.OpenPorts, true
}

// SetOpenPorts gets a reference to the given []int64 and assigns it to the OpenPorts field.
func (o *UpdateNetworkConfigRequest2) SetOpenPorts(v []int64) {
	o.OpenPorts = v
}

// GetPrivateNetworkingConfiguration returns the PrivateNetworkingConfiguration field value if set, zero value otherwise.
func (o *UpdateNetworkConfigRequest2) GetPrivateNetworkingConfiguration() PrivateNetworkingConfiguration {
	if o == nil || IsNil(o.PrivateNetworkingConfiguration) {
		var ret PrivateNetworkingConfiguration
		return ret
	}
	return *o.PrivateNetworkingConfiguration
}

// GetPrivateNetworkingConfigurationOk returns a tuple with the PrivateNetworkingConfiguration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNetworkConfigRequest2) GetPrivateNetworkingConfigurationOk() (*PrivateNetworkingConfiguration, bool) {
	if o == nil || IsNil(o.PrivateNetworkingConfiguration) {
		return nil, false
	}
	return o.PrivateNetworkingConfiguration, true
}

// SetPrivateNetworkingConfiguration gets a reference to the given PrivateNetworkingConfiguration and assigns it to the PrivateNetworkingConfiguration field.
func (o *UpdateNetworkConfigRequest2) SetPrivateNetworkingConfiguration(v PrivateNetworkingConfiguration) {
	o.PrivateNetworkingConfiguration = &v
}

// GetPublicNetworkingConfiguration returns the PublicNetworkingConfiguration field value if set, zero value otherwise.
func (o *UpdateNetworkConfigRequest2) GetPublicNetworkingConfiguration() PublicNetworkingConfiguration {
	if o == nil || IsNil(o.PublicNetworkingConfiguration) {
		var ret PublicNetworkingConfiguration
		return ret
	}
	return *o.PublicNetworkingConfiguration
}

// GetPublicNetworkingConfigurationOk returns a tuple with the PublicNetworkingConfiguration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNetworkConfigRequest2) GetPublicNetworkingConfigurationOk() (*PublicNetworkingConfiguration, bool) {
	if o == nil || IsNil(o.PublicNetworkingConfiguration) {
		return nil, false
	}
	return o.PublicNetworkingConfiguration, true
}

// SetPublicNetworkingConfiguration gets a reference to the given PublicNetworkingConfiguration and assigns it to the PublicNetworkingConfiguration field.
func (o *UpdateNetworkConfigRequest2) SetPublicNetworkingConfiguration(v PublicNetworkingConfiguration) {
	o.PublicNetworkingConfiguration = &v
}

// GetStableEgressIP returns the StableEgressIP field value if set, zero value otherwise.
func (o *UpdateNetworkConfigRequest2) GetStableEgressIP() bool {
	if o == nil || IsNil(o.StableEgressIP) {
		var ret bool
		return ret
	}
	return *o.StableEgressIP
}

// GetStableEgressIPOk returns a tuple with the StableEgressIP field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNetworkConfigRequest2) GetStableEgressIPOk() (*bool, bool) {
	if o == nil || IsNil(o.StableEgressIP) {
		return nil, false
	}
	return o.StableEgressIP, true
}

// SetStableEgressIP gets a reference to the given bool and assigns it to the StableEgressIP field.
func (o *UpdateNetworkConfigRequest2) SetStableEgressIP(v bool) {
	o.StableEgressIP = &v
}

// GetTlsTerminationPort returns the TlsTerminationPort field value if set, zero value otherwise.
func (o *UpdateNetworkConfigRequest2) GetTlsTerminationPort() int64 {
	if o == nil || IsNil(o.TlsTerminationPort) {
		var ret int64
		return ret
	}
	return *o.TlsTerminationPort
}

// GetTlsTerminationPortOk returns a tuple with the TlsTerminationPort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNetworkConfigRequest2) GetTlsTerminationPortOk() (*int64, bool) {
	if o == nil || IsNil(o.TlsTerminationPort) {
		return nil, false
	}
	return o.TlsTerminationPort, true
}

// SetTlsTerminationPort gets a reference to the given int64 and assigns it to the TlsTerminationPort field.
func (o *UpdateNetworkConfigRequest2) SetTlsTerminationPort(v int64) {
	o.TlsTerminationPort = &v
}

// GetZoneConfiguration returns the ZoneConfiguration field value if set, zero value otherwise.
func (o *UpdateNetworkConfigRequest2) GetZoneConfiguration() string {
	if o == nil || IsNil(o.ZoneConfiguration) {
		var ret string
		return ret
	}
	return *o.ZoneConfiguration
}

// GetZoneConfigurationOk returns a tuple with the ZoneConfiguration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNetworkConfigRequest2) GetZoneConfigurationOk() (*string, bool) {
	if o == nil || IsNil(o.ZoneConfiguration) {
		return nil, false
	}
	return o.ZoneConfiguration, true
}

// SetZoneConfiguration gets a reference to the given string and assigns it to the ZoneConfiguration field.
func (o *UpdateNetworkConfigRequest2) SetZoneConfiguration(v string) {
	o.ZoneConfiguration = &v
}

func (o UpdateNetworkConfigRequest2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateNetworkConfigRequest2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.EndpointPerReplica) {
		toSerialize["endpointPerReplica"] = o.EndpointPerReplica
	}
	if !IsNil(o.Internal) {
		toSerialize["internal"] = o.Internal
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.OpenPorts) {
		toSerialize["openPorts"] = o.OpenPorts
	}
	if !IsNil(o.PrivateNetworkingConfiguration) {
		toSerialize["privateNetworkingConfiguration"] = o.PrivateNetworkingConfiguration
	}
	if !IsNil(o.PublicNetworkingConfiguration) {
		toSerialize["publicNetworkingConfiguration"] = o.PublicNetworkingConfiguration
	}
	if !IsNil(o.StableEgressIP) {
		toSerialize["stableEgressIP"] = o.StableEgressIP
	}
	if !IsNil(o.TlsTerminationPort) {
		toSerialize["tlsTerminationPort"] = o.TlsTerminationPort
	}
	if !IsNil(o.ZoneConfiguration) {
		toSerialize["zoneConfiguration"] = o.ZoneConfiguration
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateNetworkConfigRequest2) UnmarshalJSON(data []byte) (err error) {
	varUpdateNetworkConfigRequest2 := _UpdateNetworkConfigRequest2{}

	err = json.Unmarshal(data, &varUpdateNetworkConfigRequest2)

	if err != nil {
		return err
	}

	*o = UpdateNetworkConfigRequest2(varUpdateNetworkConfigRequest2)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "description")
		delete(additionalProperties, "endpointPerReplica")
		delete(additionalProperties, "internal")
		delete(additionalProperties, "name")
		delete(additionalProperties, "openPorts")
		delete(additionalProperties, "privateNetworkingConfiguration")
		delete(additionalProperties, "publicNetworkingConfiguration")
		delete(additionalProperties, "stableEgressIP")
		delete(additionalProperties, "tlsTerminationPort")
		delete(additionalProperties, "zoneConfiguration")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateNetworkConfigRequest2 struct {
	value *UpdateNetworkConfigRequest2
	isSet bool
}

func (v NullableUpdateNetworkConfigRequest2) Get() *UpdateNetworkConfigRequest2 {
	return v.value
}

func (v *NullableUpdateNetworkConfigRequest2) Set(val *UpdateNetworkConfigRequest2) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateNetworkConfigRequest2) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateNetworkConfigRequest2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateNetworkConfigRequest2(val *UpdateNetworkConfigRequest2) *NullableUpdateNetworkConfigRequest2 {
	return &NullableUpdateNetworkConfigRequest2{value: val, isSet: true}
}

func (v NullableUpdateNetworkConfigRequest2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateNetworkConfigRequest2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


