/*
Omnistrate Registration API

REST API for Omnistrate Service Registration

API version: 2022-09-01-00
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
	"fmt"
)

// checks if the SetActiveAccountConfigRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetActiveAccountConfigRequest{}

// SetActiveAccountConfigRequest struct for SetActiveAccountConfigRequest
type SetActiveAccountConfigRequest struct {
	// ID of an Account Config
	AccountConfigId string `json:"accountConfigId"`
	// ID of a Service Model
	Id string `json:"id"`
	// ID of a Service
	ServiceId string `json:"serviceId"`
	// JWT token used to perform authorization
	Token string `json:"token"`
	AdditionalProperties map[string]interface{}
}

type _SetActiveAccountConfigRequest SetActiveAccountConfigRequest

// NewSetActiveAccountConfigRequest instantiates a new SetActiveAccountConfigRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetActiveAccountConfigRequest(accountConfigId string, id string, serviceId string, token string) *SetActiveAccountConfigRequest {
	this := SetActiveAccountConfigRequest{}
	this.AccountConfigId = accountConfigId
	this.Id = id
	this.ServiceId = serviceId
	this.Token = token
	return &this
}

// NewSetActiveAccountConfigRequestWithDefaults instantiates a new SetActiveAccountConfigRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetActiveAccountConfigRequestWithDefaults() *SetActiveAccountConfigRequest {
	this := SetActiveAccountConfigRequest{}
	return &this
}

// GetAccountConfigId returns the AccountConfigId field value
func (o *SetActiveAccountConfigRequest) GetAccountConfigId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountConfigId
}

// GetAccountConfigIdOk returns a tuple with the AccountConfigId field value
// and a boolean to check if the value has been set.
func (o *SetActiveAccountConfigRequest) GetAccountConfigIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountConfigId, true
}

// SetAccountConfigId sets field value
func (o *SetActiveAccountConfigRequest) SetAccountConfigId(v string) {
	o.AccountConfigId = v
}

// GetId returns the Id field value
func (o *SetActiveAccountConfigRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SetActiveAccountConfigRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SetActiveAccountConfigRequest) SetId(v string) {
	o.Id = v
}

// GetServiceId returns the ServiceId field value
func (o *SetActiveAccountConfigRequest) GetServiceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ServiceId
}

// GetServiceIdOk returns a tuple with the ServiceId field value
// and a boolean to check if the value has been set.
func (o *SetActiveAccountConfigRequest) GetServiceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceId, true
}

// SetServiceId sets field value
func (o *SetActiveAccountConfigRequest) SetServiceId(v string) {
	o.ServiceId = v
}

// GetToken returns the Token field value
func (o *SetActiveAccountConfigRequest) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *SetActiveAccountConfigRequest) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *SetActiveAccountConfigRequest) SetToken(v string) {
	o.Token = v
}

func (o SetActiveAccountConfigRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetActiveAccountConfigRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["accountConfigId"] = o.AccountConfigId
	toSerialize["id"] = o.Id
	toSerialize["serviceId"] = o.ServiceId
	toSerialize["token"] = o.Token

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SetActiveAccountConfigRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"accountConfigId",
		"id",
		"serviceId",
		"token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSetActiveAccountConfigRequest := _SetActiveAccountConfigRequest{}

	err = json.Unmarshal(data, &varSetActiveAccountConfigRequest)

	if err != nil {
		return err
	}

	*o = SetActiveAccountConfigRequest(varSetActiveAccountConfigRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "accountConfigId")
		delete(additionalProperties, "id")
		delete(additionalProperties, "serviceId")
		delete(additionalProperties, "token")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSetActiveAccountConfigRequest struct {
	value *SetActiveAccountConfigRequest
	isSet bool
}

func (v NullableSetActiveAccountConfigRequest) Get() *SetActiveAccountConfigRequest {
	return v.value
}

func (v *NullableSetActiveAccountConfigRequest) Set(val *SetActiveAccountConfigRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSetActiveAccountConfigRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSetActiveAccountConfigRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetActiveAccountConfigRequest(val *SetActiveAccountConfigRequest) *NullableSetActiveAccountConfigRequest {
	return &NullableSetActiveAccountConfigRequest{value: val, isSet: true}
}

func (v NullableSetActiveAccountConfigRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetActiveAccountConfigRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


