/*
Omnistrate Registration API

REST API for Omnistrate Service Registration

API version: 2022-09-01-00
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the ManagedReleaseRevision2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManagedReleaseRevision2{}

// ManagedReleaseRevision2 struct for ManagedReleaseRevision2
type ManagedReleaseRevision2 struct {
	ArtifactCount int64 `json:"artifactCount"`
	Artifacts []ManagedReleaseArtifact3 `json:"artifacts,omitempty"`
	BundleRevisionId string `json:"bundleRevisionId" validate:"regexp=^oabr-[a-zA-Z0-9-]+$"`
	BundleVersion string `json:"bundleVersion"`
	ComponentRevisions []ManagedReleaseComponentRevision `json:"componentRevisions"`
	ContentHash *string `json:"contentHash,omitempty" validate:"regexp=^sha256:[a-fA-F0-9]{64}$"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	LastError *string `json:"lastError,omitempty"`
	LastTransitionTime *time.Time `json:"lastTransitionTime,omitempty"`
	ReleaseComponent string `json:"releaseComponent"`
	ReleaseSequence int64 `json:"releaseSequence"`
	ReleasedAt *time.Time `json:"releasedAt,omitempty"`
	Status string `json:"status"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	WorkflowId *string `json:"workflowId,omitempty"`
	WorkflowRunId *string `json:"workflowRunId,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ManagedReleaseRevision2 ManagedReleaseRevision2

// NewManagedReleaseRevision2 instantiates a new ManagedReleaseRevision2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManagedReleaseRevision2(artifactCount int64, bundleRevisionId string, bundleVersion string, componentRevisions []ManagedReleaseComponentRevision, releaseComponent string, releaseSequence int64, status string) *ManagedReleaseRevision2 {
	this := ManagedReleaseRevision2{}
	this.ArtifactCount = artifactCount
	this.BundleRevisionId = bundleRevisionId
	this.BundleVersion = bundleVersion
	this.ComponentRevisions = componentRevisions
	this.ReleaseComponent = releaseComponent
	this.ReleaseSequence = releaseSequence
	this.Status = status
	return &this
}

// NewManagedReleaseRevision2WithDefaults instantiates a new ManagedReleaseRevision2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManagedReleaseRevision2WithDefaults() *ManagedReleaseRevision2 {
	this := ManagedReleaseRevision2{}
	return &this
}

// GetArtifactCount returns the ArtifactCount field value
func (o *ManagedReleaseRevision2) GetArtifactCount() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ArtifactCount
}

// GetArtifactCountOk returns a tuple with the ArtifactCount field value
// and a boolean to check if the value has been set.
func (o *ManagedReleaseRevision2) GetArtifactCountOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ArtifactCount, true
}

// SetArtifactCount sets field value
func (o *ManagedReleaseRevision2) SetArtifactCount(v int64) {
	o.ArtifactCount = v
}

// GetArtifacts returns the Artifacts field value if set, zero value otherwise.
func (o *ManagedReleaseRevision2) GetArtifacts() []ManagedReleaseArtifact3 {
	if o == nil || IsNil(o.Artifacts) {
		var ret []ManagedReleaseArtifact3
		return ret
	}
	return o.Artifacts
}

// GetArtifactsOk returns a tuple with the Artifacts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagedReleaseRevision2) GetArtifactsOk() ([]ManagedReleaseArtifact3, bool) {
	if o == nil || IsNil(o.Artifacts) {
		return nil, false
	}
	return o.Artifacts, true
}

// SetArtifacts gets a reference to the given []ManagedReleaseArtifact3 and assigns it to the Artifacts field.
func (o *ManagedReleaseRevision2) SetArtifacts(v []ManagedReleaseArtifact3) {
	o.Artifacts = v
}

// GetBundleRevisionId returns the BundleRevisionId field value
func (o *ManagedReleaseRevision2) GetBundleRevisionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BundleRevisionId
}

// GetBundleRevisionIdOk returns a tuple with the BundleRevisionId field value
// and a boolean to check if the value has been set.
func (o *ManagedReleaseRevision2) GetBundleRevisionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BundleRevisionId, true
}

// SetBundleRevisionId sets field value
func (o *ManagedReleaseRevision2) SetBundleRevisionId(v string) {
	o.BundleRevisionId = v
}

// GetBundleVersion returns the BundleVersion field value
func (o *ManagedReleaseRevision2) GetBundleVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BundleVersion
}

// GetBundleVersionOk returns a tuple with the BundleVersion field value
// and a boolean to check if the value has been set.
func (o *ManagedReleaseRevision2) GetBundleVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BundleVersion, true
}

// SetBundleVersion sets field value
func (o *ManagedReleaseRevision2) SetBundleVersion(v string) {
	o.BundleVersion = v
}

// GetComponentRevisions returns the ComponentRevisions field value
func (o *ManagedReleaseRevision2) GetComponentRevisions() []ManagedReleaseComponentRevision {
	if o == nil {
		var ret []ManagedReleaseComponentRevision
		return ret
	}

	return o.ComponentRevisions
}

// GetComponentRevisionsOk returns a tuple with the ComponentRevisions field value
// and a boolean to check if the value has been set.
func (o *ManagedReleaseRevision2) GetComponentRevisionsOk() ([]ManagedReleaseComponentRevision, bool) {
	if o == nil {
		return nil, false
	}
	return o.ComponentRevisions, true
}

// SetComponentRevisions sets field value
func (o *ManagedReleaseRevision2) SetComponentRevisions(v []ManagedReleaseComponentRevision) {
	o.ComponentRevisions = v
}

// GetContentHash returns the ContentHash field value if set, zero value otherwise.
func (o *ManagedReleaseRevision2) GetContentHash() string {
	if o == nil || IsNil(o.ContentHash) {
		var ret string
		return ret
	}
	return *o.ContentHash
}

// GetContentHashOk returns a tuple with the ContentHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagedReleaseRevision2) GetContentHashOk() (*string, bool) {
	if o == nil || IsNil(o.ContentHash) {
		return nil, false
	}
	return o.ContentHash, true
}

// SetContentHash gets a reference to the given string and assigns it to the ContentHash field.
func (o *ManagedReleaseRevision2) SetContentHash(v string) {
	o.ContentHash = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *ManagedReleaseRevision2) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagedReleaseRevision2) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *ManagedReleaseRevision2) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetLastError returns the LastError field value if set, zero value otherwise.
func (o *ManagedReleaseRevision2) GetLastError() string {
	if o == nil || IsNil(o.LastError) {
		var ret string
		return ret
	}
	return *o.LastError
}

// GetLastErrorOk returns a tuple with the LastError field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagedReleaseRevision2) GetLastErrorOk() (*string, bool) {
	if o == nil || IsNil(o.LastError) {
		return nil, false
	}
	return o.LastError, true
}

// SetLastError gets a reference to the given string and assigns it to the LastError field.
func (o *ManagedReleaseRevision2) SetLastError(v string) {
	o.LastError = &v
}

// GetLastTransitionTime returns the LastTransitionTime field value if set, zero value otherwise.
func (o *ManagedReleaseRevision2) GetLastTransitionTime() time.Time {
	if o == nil || IsNil(o.LastTransitionTime) {
		var ret time.Time
		return ret
	}
	return *o.LastTransitionTime
}

// GetLastTransitionTimeOk returns a tuple with the LastTransitionTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagedReleaseRevision2) GetLastTransitionTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastTransitionTime) {
		return nil, false
	}
	return o.LastTransitionTime, true
}

// SetLastTransitionTime gets a reference to the given time.Time and assigns it to the LastTransitionTime field.
func (o *ManagedReleaseRevision2) SetLastTransitionTime(v time.Time) {
	o.LastTransitionTime = &v
}

// GetReleaseComponent returns the ReleaseComponent field value
func (o *ManagedReleaseRevision2) GetReleaseComponent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ReleaseComponent
}

// GetReleaseComponentOk returns a tuple with the ReleaseComponent field value
// and a boolean to check if the value has been set.
func (o *ManagedReleaseRevision2) GetReleaseComponentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReleaseComponent, true
}

// SetReleaseComponent sets field value
func (o *ManagedReleaseRevision2) SetReleaseComponent(v string) {
	o.ReleaseComponent = v
}

// GetReleaseSequence returns the ReleaseSequence field value
func (o *ManagedReleaseRevision2) GetReleaseSequence() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ReleaseSequence
}

// GetReleaseSequenceOk returns a tuple with the ReleaseSequence field value
// and a boolean to check if the value has been set.
func (o *ManagedReleaseRevision2) GetReleaseSequenceOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReleaseSequence, true
}

// SetReleaseSequence sets field value
func (o *ManagedReleaseRevision2) SetReleaseSequence(v int64) {
	o.ReleaseSequence = v
}

// GetReleasedAt returns the ReleasedAt field value if set, zero value otherwise.
func (o *ManagedReleaseRevision2) GetReleasedAt() time.Time {
	if o == nil || IsNil(o.ReleasedAt) {
		var ret time.Time
		return ret
	}
	return *o.ReleasedAt
}

// GetReleasedAtOk returns a tuple with the ReleasedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagedReleaseRevision2) GetReleasedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ReleasedAt) {
		return nil, false
	}
	return o.ReleasedAt, true
}

// SetReleasedAt gets a reference to the given time.Time and assigns it to the ReleasedAt field.
func (o *ManagedReleaseRevision2) SetReleasedAt(v time.Time) {
	o.ReleasedAt = &v
}

// GetStatus returns the Status field value
func (o *ManagedReleaseRevision2) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ManagedReleaseRevision2) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ManagedReleaseRevision2) SetStatus(v string) {
	o.Status = v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *ManagedReleaseRevision2) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagedReleaseRevision2) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *ManagedReleaseRevision2) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetWorkflowId returns the WorkflowId field value if set, zero value otherwise.
func (o *ManagedReleaseRevision2) GetWorkflowId() string {
	if o == nil || IsNil(o.WorkflowId) {
		var ret string
		return ret
	}
	return *o.WorkflowId
}

// GetWorkflowIdOk returns a tuple with the WorkflowId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagedReleaseRevision2) GetWorkflowIdOk() (*string, bool) {
	if o == nil || IsNil(o.WorkflowId) {
		return nil, false
	}
	return o.WorkflowId, true
}

// SetWorkflowId gets a reference to the given string and assigns it to the WorkflowId field.
func (o *ManagedReleaseRevision2) SetWorkflowId(v string) {
	o.WorkflowId = &v
}

// GetWorkflowRunId returns the WorkflowRunId field value if set, zero value otherwise.
func (o *ManagedReleaseRevision2) GetWorkflowRunId() string {
	if o == nil || IsNil(o.WorkflowRunId) {
		var ret string
		return ret
	}
	return *o.WorkflowRunId
}

// GetWorkflowRunIdOk returns a tuple with the WorkflowRunId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagedReleaseRevision2) GetWorkflowRunIdOk() (*string, bool) {
	if o == nil || IsNil(o.WorkflowRunId) {
		return nil, false
	}
	return o.WorkflowRunId, true
}

// SetWorkflowRunId gets a reference to the given string and assigns it to the WorkflowRunId field.
func (o *ManagedReleaseRevision2) SetWorkflowRunId(v string) {
	o.WorkflowRunId = &v
}

func (o ManagedReleaseRevision2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManagedReleaseRevision2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["artifactCount"] = o.ArtifactCount
	if !IsNil(o.Artifacts) {
		toSerialize["artifacts"] = o.Artifacts
	}
	toSerialize["bundleRevisionId"] = o.BundleRevisionId
	toSerialize["bundleVersion"] = o.BundleVersion
	toSerialize["componentRevisions"] = o.ComponentRevisions
	if !IsNil(o.ContentHash) {
		toSerialize["contentHash"] = o.ContentHash
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.LastError) {
		toSerialize["lastError"] = o.LastError
	}
	if !IsNil(o.LastTransitionTime) {
		toSerialize["lastTransitionTime"] = o.LastTransitionTime
	}
	toSerialize["releaseComponent"] = o.ReleaseComponent
	toSerialize["releaseSequence"] = o.ReleaseSequence
	if !IsNil(o.ReleasedAt) {
		toSerialize["releasedAt"] = o.ReleasedAt
	}
	toSerialize["status"] = o.Status
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	if !IsNil(o.WorkflowId) {
		toSerialize["workflowId"] = o.WorkflowId
	}
	if !IsNil(o.WorkflowRunId) {
		toSerialize["workflowRunId"] = o.WorkflowRunId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ManagedReleaseRevision2) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"artifactCount",
		"bundleRevisionId",
		"bundleVersion",
		"componentRevisions",
		"releaseComponent",
		"releaseSequence",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varManagedReleaseRevision2 := _ManagedReleaseRevision2{}

	err = json.Unmarshal(data, &varManagedReleaseRevision2)

	if err != nil {
		return err
	}

	*o = ManagedReleaseRevision2(varManagedReleaseRevision2)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "artifactCount")
		delete(additionalProperties, "artifacts")
		delete(additionalProperties, "bundleRevisionId")
		delete(additionalProperties, "bundleVersion")
		delete(additionalProperties, "componentRevisions")
		delete(additionalProperties, "contentHash")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "lastError")
		delete(additionalProperties, "lastTransitionTime")
		delete(additionalProperties, "releaseComponent")
		delete(additionalProperties, "releaseSequence")
		delete(additionalProperties, "releasedAt")
		delete(additionalProperties, "status")
		delete(additionalProperties, "updatedAt")
		delete(additionalProperties, "workflowId")
		delete(additionalProperties, "workflowRunId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableManagedReleaseRevision2 struct {
	value *ManagedReleaseRevision2
	isSet bool
}

func (v NullableManagedReleaseRevision2) Get() *ManagedReleaseRevision2 {
	return v.value
}

func (v *NullableManagedReleaseRevision2) Set(val *ManagedReleaseRevision2) {
	v.value = val
	v.isSet = true
}

func (v NullableManagedReleaseRevision2) IsSet() bool {
	return v.isSet
}

func (v *NullableManagedReleaseRevision2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManagedReleaseRevision2(val *ManagedReleaseRevision2) *NullableManagedReleaseRevision2 {
	return &NullableManagedReleaseRevision2{value: val, isSet: true}
}

func (v NullableManagedReleaseRevision2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManagedReleaseRevision2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

