/*
Omnistrate Registration API

REST API for Omnistrate Service Registration

API version: 2022-09-01-00
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateProductTierRequest2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateProductTierRequest2{}

// CreateProductTierRequest2 struct for CreateProductTierRequest2
type CreateProductTierRequest2 struct {
	// Auto approve subscription or not
	AutoApproveSubscription *bool `json:"autoApproveSubscription,omitempty"`
	// The AWS regions that this product tier is available on
	AwsRegions []string `json:"awsRegions,omitempty"`
	// A brief description of the product tier
	Description string `json:"description"`
	// Documentation
	Documentation *string `json:"documentation,omitempty"`
	// The GCP regions that this product tier is available on
	GcpRegions []string `json:"gcpRegions,omitempty"`
	// Create the product tier in a disabled state. Enabling the product tier will let end-customers subscribe and use the service plan.
	IsDisabled *bool `json:"isDisabled,omitempty"`
	// Name of the product tier
	Name string `json:"name"`
	// A brief description for the end user of the product tier
	PlanDescription string `json:"planDescription"`
	// Pricing
	Pricing interface{} `json:"pricing,omitempty"`
	// Service model ID
	ServiceModelId string `json:"serviceModelId"`
	// Support
	Support *string `json:"support,omitempty"`
	// Tier type
	TierType string `json:"tierType"`
	AdditionalProperties map[string]interface{}
}

type _CreateProductTierRequest2 CreateProductTierRequest2

// NewCreateProductTierRequest2 instantiates a new CreateProductTierRequest2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateProductTierRequest2(description string, name string, planDescription string, serviceModelId string, tierType string) *CreateProductTierRequest2 {
	this := CreateProductTierRequest2{}
	this.Description = description
	this.Name = name
	this.PlanDescription = planDescription
	this.ServiceModelId = serviceModelId
	this.TierType = tierType
	return &this
}

// NewCreateProductTierRequest2WithDefaults instantiates a new CreateProductTierRequest2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateProductTierRequest2WithDefaults() *CreateProductTierRequest2 {
	this := CreateProductTierRequest2{}
	return &this
}

// GetAutoApproveSubscription returns the AutoApproveSubscription field value if set, zero value otherwise.
func (o *CreateProductTierRequest2) GetAutoApproveSubscription() bool {
	if o == nil || IsNil(o.AutoApproveSubscription) {
		var ret bool
		return ret
	}
	return *o.AutoApproveSubscription
}

// GetAutoApproveSubscriptionOk returns a tuple with the AutoApproveSubscription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateProductTierRequest2) GetAutoApproveSubscriptionOk() (*bool, bool) {
	if o == nil || IsNil(o.AutoApproveSubscription) {
		return nil, false
	}
	return o.AutoApproveSubscription, true
}

// SetAutoApproveSubscription gets a reference to the given bool and assigns it to the AutoApproveSubscription field.
func (o *CreateProductTierRequest2) SetAutoApproveSubscription(v bool) {
	o.AutoApproveSubscription = &v
}

// GetAwsRegions returns the AwsRegions field value if set, zero value otherwise.
func (o *CreateProductTierRequest2) GetAwsRegions() []string {
	if o == nil || IsNil(o.AwsRegions) {
		var ret []string
		return ret
	}
	return o.AwsRegions
}

// GetAwsRegionsOk returns a tuple with the AwsRegions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateProductTierRequest2) GetAwsRegionsOk() ([]string, bool) {
	if o == nil || IsNil(o.AwsRegions) {
		return nil, false
	}
	return o.AwsRegions, true
}

// SetAwsRegions gets a reference to the given []string and assigns it to the AwsRegions field.
func (o *CreateProductTierRequest2) SetAwsRegions(v []string) {
	o.AwsRegions = v
}

// GetDescription returns the Description field value
func (o *CreateProductTierRequest2) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *CreateProductTierRequest2) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *CreateProductTierRequest2) SetDescription(v string) {
	o.Description = v
}

// GetDocumentation returns the Documentation field value if set, zero value otherwise.
func (o *CreateProductTierRequest2) GetDocumentation() string {
	if o == nil || IsNil(o.Documentation) {
		var ret string
		return ret
	}
	return *o.Documentation
}

// GetDocumentationOk returns a tuple with the Documentation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateProductTierRequest2) GetDocumentationOk() (*string, bool) {
	if o == nil || IsNil(o.Documentation) {
		return nil, false
	}
	return o.Documentation, true
}

// SetDocumentation gets a reference to the given string and assigns it to the Documentation field.
func (o *CreateProductTierRequest2) SetDocumentation(v string) {
	o.Documentation = &v
}

// GetGcpRegions returns the GcpRegions field value if set, zero value otherwise.
func (o *CreateProductTierRequest2) GetGcpRegions() []string {
	if o == nil || IsNil(o.GcpRegions) {
		var ret []string
		return ret
	}
	return o.GcpRegions
}

// GetGcpRegionsOk returns a tuple with the GcpRegions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateProductTierRequest2) GetGcpRegionsOk() ([]string, bool) {
	if o == nil || IsNil(o.GcpRegions) {
		return nil, false
	}
	return o.GcpRegions, true
}

// SetGcpRegions gets a reference to the given []string and assigns it to the GcpRegions field.
func (o *CreateProductTierRequest2) SetGcpRegions(v []string) {
	o.GcpRegions = v
}

// GetIsDisabled returns the IsDisabled field value if set, zero value otherwise.
func (o *CreateProductTierRequest2) GetIsDisabled() bool {
	if o == nil || IsNil(o.IsDisabled) {
		var ret bool
		return ret
	}
	return *o.IsDisabled
}

// GetIsDisabledOk returns a tuple with the IsDisabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateProductTierRequest2) GetIsDisabledOk() (*bool, bool) {
	if o == nil || IsNil(o.IsDisabled) {
		return nil, false
	}
	return o.IsDisabled, true
}

// SetIsDisabled gets a reference to the given bool and assigns it to the IsDisabled field.
func (o *CreateProductTierRequest2) SetIsDisabled(v bool) {
	o.IsDisabled = &v
}

// GetName returns the Name field value
func (o *CreateProductTierRequest2) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateProductTierRequest2) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateProductTierRequest2) SetName(v string) {
	o.Name = v
}

// GetPlanDescription returns the PlanDescription field value
func (o *CreateProductTierRequest2) GetPlanDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PlanDescription
}

// GetPlanDescriptionOk returns a tuple with the PlanDescription field value
// and a boolean to check if the value has been set.
func (o *CreateProductTierRequest2) GetPlanDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlanDescription, true
}

// SetPlanDescription sets field value
func (o *CreateProductTierRequest2) SetPlanDescription(v string) {
	o.PlanDescription = v
}

// GetPricing returns the Pricing field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateProductTierRequest2) GetPricing() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Pricing
}

// GetPricingOk returns a tuple with the Pricing field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateProductTierRequest2) GetPricingOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Pricing) {
		return nil, false
	}
	return &o.Pricing, true
}

// SetPricing gets a reference to the given interface{} and assigns it to the Pricing field.
func (o *CreateProductTierRequest2) SetPricing(v interface{}) {
	o.Pricing = v
}

// GetServiceModelId returns the ServiceModelId field value
func (o *CreateProductTierRequest2) GetServiceModelId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ServiceModelId
}

// GetServiceModelIdOk returns a tuple with the ServiceModelId field value
// and a boolean to check if the value has been set.
func (o *CreateProductTierRequest2) GetServiceModelIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceModelId, true
}

// SetServiceModelId sets field value
func (o *CreateProductTierRequest2) SetServiceModelId(v string) {
	o.ServiceModelId = v
}

// GetSupport returns the Support field value if set, zero value otherwise.
func (o *CreateProductTierRequest2) GetSupport() string {
	if o == nil || IsNil(o.Support) {
		var ret string
		return ret
	}
	return *o.Support
}

// GetSupportOk returns a tuple with the Support field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateProductTierRequest2) GetSupportOk() (*string, bool) {
	if o == nil || IsNil(o.Support) {
		return nil, false
	}
	return o.Support, true
}

// SetSupport gets a reference to the given string and assigns it to the Support field.
func (o *CreateProductTierRequest2) SetSupport(v string) {
	o.Support = &v
}

// GetTierType returns the TierType field value
func (o *CreateProductTierRequest2) GetTierType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TierType
}

// GetTierTypeOk returns a tuple with the TierType field value
// and a boolean to check if the value has been set.
func (o *CreateProductTierRequest2) GetTierTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TierType, true
}

// SetTierType sets field value
func (o *CreateProductTierRequest2) SetTierType(v string) {
	o.TierType = v
}

func (o CreateProductTierRequest2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateProductTierRequest2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AutoApproveSubscription) {
		toSerialize["autoApproveSubscription"] = o.AutoApproveSubscription
	}
	if !IsNil(o.AwsRegions) {
		toSerialize["awsRegions"] = o.AwsRegions
	}
	toSerialize["description"] = o.Description
	if !IsNil(o.Documentation) {
		toSerialize["documentation"] = o.Documentation
	}
	if !IsNil(o.GcpRegions) {
		toSerialize["gcpRegions"] = o.GcpRegions
	}
	if !IsNil(o.IsDisabled) {
		toSerialize["isDisabled"] = o.IsDisabled
	}
	toSerialize["name"] = o.Name
	toSerialize["planDescription"] = o.PlanDescription
	if o.Pricing != nil {
		toSerialize["pricing"] = o.Pricing
	}
	toSerialize["serviceModelId"] = o.ServiceModelId
	if !IsNil(o.Support) {
		toSerialize["support"] = o.Support
	}
	toSerialize["tierType"] = o.TierType

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateProductTierRequest2) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"description",
		"name",
		"planDescription",
		"serviceModelId",
		"tierType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateProductTierRequest2 := _CreateProductTierRequest2{}

	err = json.Unmarshal(data, &varCreateProductTierRequest2)

	if err != nil {
		return err
	}

	*o = CreateProductTierRequest2(varCreateProductTierRequest2)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "autoApproveSubscription")
		delete(additionalProperties, "awsRegions")
		delete(additionalProperties, "description")
		delete(additionalProperties, "documentation")
		delete(additionalProperties, "gcpRegions")
		delete(additionalProperties, "isDisabled")
		delete(additionalProperties, "name")
		delete(additionalProperties, "planDescription")
		delete(additionalProperties, "pricing")
		delete(additionalProperties, "serviceModelId")
		delete(additionalProperties, "support")
		delete(additionalProperties, "tierType")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateProductTierRequest2 struct {
	value *CreateProductTierRequest2
	isSet bool
}

func (v NullableCreateProductTierRequest2) Get() *CreateProductTierRequest2 {
	return v.value
}

func (v *NullableCreateProductTierRequest2) Set(val *CreateProductTierRequest2) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateProductTierRequest2) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateProductTierRequest2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateProductTierRequest2(val *CreateProductTierRequest2) *NullableCreateProductTierRequest2 {
	return &NullableCreateProductTierRequest2{value: val, isSet: true}
}

func (v NullableCreateProductTierRequest2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateProductTierRequest2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


