/*
Omnistrate Registration API

REST API for Omnistrate Service Registration

API version: 2022-09-01-00
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
	"fmt"
)

// checks if the ValidationCheck type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ValidationCheck{}

// ValidationCheck The outcome of one validation check category.
type ValidationCheck struct {
	// The validation check category. Every category is reported on every response; categories that the submitted specification does not exercise are reported explicitly as NOT_APPLICABLE rather than omitted.
	Name string `json:"name"`
	// The outcome of a single validation check category. PASSED means the category completed with no error. FAILED means the category produced at least one error diagnostic. INCOMPLETE means the category could not be completed, including when it was blocked by failed syntax or normalization. NOT_APPLICABLE means the submitted specification does not exercise the category at all.
	Status string `json:"status"`
	AdditionalProperties map[string]interface{}
}

type _ValidationCheck ValidationCheck

// NewValidationCheck instantiates a new ValidationCheck object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewValidationCheck(name string, status string) *ValidationCheck {
	this := ValidationCheck{}
	this.Name = name
	this.Status = status
	return &this
}

// NewValidationCheckWithDefaults instantiates a new ValidationCheck object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewValidationCheckWithDefaults() *ValidationCheck {
	this := ValidationCheck{}
	return &this
}

// GetName returns the Name field value
func (o *ValidationCheck) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ValidationCheck) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ValidationCheck) SetName(v string) {
	o.Name = v
}

// GetStatus returns the Status field value
func (o *ValidationCheck) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ValidationCheck) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ValidationCheck) SetStatus(v string) {
	o.Status = v
}

func (o ValidationCheck) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ValidationCheck) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["status"] = o.Status

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ValidationCheck) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varValidationCheck := _ValidationCheck{}

	err = json.Unmarshal(data, &varValidationCheck)

	if err != nil {
		return err
	}

	*o = ValidationCheck(varValidationCheck)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "status")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableValidationCheck struct {
	value *ValidationCheck
	isSet bool
}

func (v NullableValidationCheck) Get() *ValidationCheck {
	return v.value
}

func (v *NullableValidationCheck) Set(val *ValidationCheck) {
	v.value = val
	v.isSet = true
}

func (v NullableValidationCheck) IsSet() bool {
	return v.isSet
}

func (v *NullableValidationCheck) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableValidationCheck(val *ValidationCheck) *NullableValidationCheck {
	return &NullableValidationCheck{value: val, isSet: true}
}

func (v NullableValidationCheck) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableValidationCheck) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

