/*
Omnistrate Fleet API

REST API for Omnistrate Fleet

API version: 2022-09-01-00
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fleet

import (
	"encoding/json"
)

// checks if the ServiceProviderEventSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceProviderEventSummary{}

// ServiceProviderEventSummary struct for ServiceProviderEventSummary
type ServiceProviderEventSummary struct {
	// The number of outstanding events by type
	EventsSummary *map[string]int64 `json:"eventsSummary,omitempty"`
}

// NewServiceProviderEventSummary instantiates a new ServiceProviderEventSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceProviderEventSummary() *ServiceProviderEventSummary {
	this := ServiceProviderEventSummary{}
	return &this
}

// NewServiceProviderEventSummaryWithDefaults instantiates a new ServiceProviderEventSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceProviderEventSummaryWithDefaults() *ServiceProviderEventSummary {
	this := ServiceProviderEventSummary{}
	return &this
}

// GetEventsSummary returns the EventsSummary field value if set, zero value otherwise.
func (o *ServiceProviderEventSummary) GetEventsSummary() map[string]int64 {
	if o == nil || IsNil(o.EventsSummary) {
		var ret map[string]int64
		return ret
	}
	return *o.EventsSummary
}

// GetEventsSummaryOk returns a tuple with the EventsSummary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceProviderEventSummary) GetEventsSummaryOk() (*map[string]int64, bool) {
	if o == nil || IsNil(o.EventsSummary) {
		return nil, false
	}
	return o.EventsSummary, true
}

// HasEventsSummary returns a boolean if a field has been set.
func (o *ServiceProviderEventSummary) HasEventsSummary() bool {
	if o != nil && !IsNil(o.EventsSummary) {
		return true
	}

	return false
}

// SetEventsSummary gets a reference to the given map[string]int64 and assigns it to the EventsSummary field.
func (o *ServiceProviderEventSummary) SetEventsSummary(v map[string]int64) {
	o.EventsSummary = &v
}

func (o ServiceProviderEventSummary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceProviderEventSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EventsSummary) {
		toSerialize["eventsSummary"] = o.EventsSummary
	}
	return toSerialize, nil
}

type NullableServiceProviderEventSummary struct {
	value *ServiceProviderEventSummary
	isSet bool
}

func (v NullableServiceProviderEventSummary) Get() *ServiceProviderEventSummary {
	return v.value
}

func (v *NullableServiceProviderEventSummary) Set(val *ServiceProviderEventSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceProviderEventSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceProviderEventSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceProviderEventSummary(val *ServiceProviderEventSummary) *NullableServiceProviderEventSummary {
	return &NullableServiceProviderEventSummary{value: val, isSet: true}
}

func (v NullableServiceProviderEventSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceProviderEventSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


