/*
Omnistrate Fleet API

REST API for Omnistrate Fleet

API version: 2022-09-01-00
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fleet

import (
	"encoding/json"
	"fmt"
)

// checks if the StartSandboxRunRequest2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StartSandboxRunRequest2{}

// StartSandboxRunRequest2 struct for StartSandboxRunRequest2
type StartSandboxRunRequest2 struct {
	// Where to deliver. Validated on write: https only, no embedded credentials, and not a private, loopback, link-local or metadata address
	ReceiverUrl string `json:"receiverUrl"`
	AdditionalProperties map[string]interface{}
}

type _StartSandboxRunRequest2 StartSandboxRunRequest2

// NewStartSandboxRunRequest2 instantiates a new StartSandboxRunRequest2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStartSandboxRunRequest2(receiverUrl string) *StartSandboxRunRequest2 {
	this := StartSandboxRunRequest2{}
	this.ReceiverUrl = receiverUrl
	return &this
}

// NewStartSandboxRunRequest2WithDefaults instantiates a new StartSandboxRunRequest2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStartSandboxRunRequest2WithDefaults() *StartSandboxRunRequest2 {
	this := StartSandboxRunRequest2{}
	return &this
}

// GetReceiverUrl returns the ReceiverUrl field value
func (o *StartSandboxRunRequest2) GetReceiverUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ReceiverUrl
}

// GetReceiverUrlOk returns a tuple with the ReceiverUrl field value
// and a boolean to check if the value has been set.
func (o *StartSandboxRunRequest2) GetReceiverUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReceiverUrl, true
}

// SetReceiverUrl sets field value
func (o *StartSandboxRunRequest2) SetReceiverUrl(v string) {
	o.ReceiverUrl = v
}

func (o StartSandboxRunRequest2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StartSandboxRunRequest2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["receiverUrl"] = o.ReceiverUrl

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *StartSandboxRunRequest2) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"receiverUrl",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStartSandboxRunRequest2 := _StartSandboxRunRequest2{}

	err = json.Unmarshal(data, &varStartSandboxRunRequest2)

	if err != nil {
		return err
	}

	*o = StartSandboxRunRequest2(varStartSandboxRunRequest2)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "receiverUrl")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableStartSandboxRunRequest2 struct {
	value *StartSandboxRunRequest2
	isSet bool
}

func (v NullableStartSandboxRunRequest2) Get() *StartSandboxRunRequest2 {
	return v.value
}

func (v *NullableStartSandboxRunRequest2) Set(val *StartSandboxRunRequest2) {
	v.value = val
	v.isSet = true
}

func (v NullableStartSandboxRunRequest2) IsSet() bool {
	return v.isSet
}

func (v *NullableStartSandboxRunRequest2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStartSandboxRunRequest2(val *StartSandboxRunRequest2) *NullableStartSandboxRunRequest2 {
	return &NullableStartSandboxRunRequest2{value: val, isSet: true}
}

func (v NullableStartSandboxRunRequest2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStartSandboxRunRequest2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


