/*
Omnistrate Fleet API

REST API for Omnistrate Fleet

API version: 2022-09-01-00
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fleet

import (
	"encoding/json"
	"fmt"
)

// checks if the FleetListAllInstanceSnapshotRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FleetListAllInstanceSnapshotRequest{}

// FleetListAllInstanceSnapshotRequest struct for FleetListAllInstanceSnapshotRequest
type FleetListAllInstanceSnapshotRequest struct {
	// ID of a Service Environment
	EnvironmentId string `json:"environmentId"`
	// ID of a Product Tier
	ProductTierId *string `json:"productTierId,omitempty"`
	// ID of a Service
	ServiceId string `json:"serviceId"`
	// The snapshot type to filter by
	SnapshotType *string `json:"snapshotType,omitempty"`
	// ID of a Subscription
	SubscriptionId *string `json:"subscriptionId,omitempty"`
	// JWT token used to perform authorization
	Token string `json:"token"`
	AdditionalProperties map[string]interface{}
}

type _FleetListAllInstanceSnapshotRequest FleetListAllInstanceSnapshotRequest

// NewFleetListAllInstanceSnapshotRequest instantiates a new FleetListAllInstanceSnapshotRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFleetListAllInstanceSnapshotRequest(environmentId string, serviceId string, token string) *FleetListAllInstanceSnapshotRequest {
	this := FleetListAllInstanceSnapshotRequest{}
	this.EnvironmentId = environmentId
	this.ServiceId = serviceId
	this.Token = token
	return &this
}

// NewFleetListAllInstanceSnapshotRequestWithDefaults instantiates a new FleetListAllInstanceSnapshotRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFleetListAllInstanceSnapshotRequestWithDefaults() *FleetListAllInstanceSnapshotRequest {
	this := FleetListAllInstanceSnapshotRequest{}
	return &this
}

// GetEnvironmentId returns the EnvironmentId field value
func (o *FleetListAllInstanceSnapshotRequest) GetEnvironmentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EnvironmentId
}

// GetEnvironmentIdOk returns a tuple with the EnvironmentId field value
// and a boolean to check if the value has been set.
func (o *FleetListAllInstanceSnapshotRequest) GetEnvironmentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EnvironmentId, true
}

// SetEnvironmentId sets field value
func (o *FleetListAllInstanceSnapshotRequest) SetEnvironmentId(v string) {
	o.EnvironmentId = v
}

// GetProductTierId returns the ProductTierId field value if set, zero value otherwise.
func (o *FleetListAllInstanceSnapshotRequest) GetProductTierId() string {
	if o == nil || IsNil(o.ProductTierId) {
		var ret string
		return ret
	}
	return *o.ProductTierId
}

// GetProductTierIdOk returns a tuple with the ProductTierId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FleetListAllInstanceSnapshotRequest) GetProductTierIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProductTierId) {
		return nil, false
	}
	return o.ProductTierId, true
}

// HasProductTierId returns a boolean if a field has been set.
func (o *FleetListAllInstanceSnapshotRequest) HasProductTierId() bool {
	if o != nil && !IsNil(o.ProductTierId) {
		return true
	}

	return false
}

// SetProductTierId gets a reference to the given string and assigns it to the ProductTierId field.
func (o *FleetListAllInstanceSnapshotRequest) SetProductTierId(v string) {
	o.ProductTierId = &v
}

// GetServiceId returns the ServiceId field value
func (o *FleetListAllInstanceSnapshotRequest) GetServiceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ServiceId
}

// GetServiceIdOk returns a tuple with the ServiceId field value
// and a boolean to check if the value has been set.
func (o *FleetListAllInstanceSnapshotRequest) GetServiceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceId, true
}

// SetServiceId sets field value
func (o *FleetListAllInstanceSnapshotRequest) SetServiceId(v string) {
	o.ServiceId = v
}

// GetSnapshotType returns the SnapshotType field value if set, zero value otherwise.
func (o *FleetListAllInstanceSnapshotRequest) GetSnapshotType() string {
	if o == nil || IsNil(o.SnapshotType) {
		var ret string
		return ret
	}
	return *o.SnapshotType
}

// GetSnapshotTypeOk returns a tuple with the SnapshotType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FleetListAllInstanceSnapshotRequest) GetSnapshotTypeOk() (*string, bool) {
	if o == nil || IsNil(o.SnapshotType) {
		return nil, false
	}
	return o.SnapshotType, true
}

// HasSnapshotType returns a boolean if a field has been set.
func (o *FleetListAllInstanceSnapshotRequest) HasSnapshotType() bool {
	if o != nil && !IsNil(o.SnapshotType) {
		return true
	}

	return false
}

// SetSnapshotType gets a reference to the given string and assigns it to the SnapshotType field.
func (o *FleetListAllInstanceSnapshotRequest) SetSnapshotType(v string) {
	o.SnapshotType = &v
}

// GetSubscriptionId returns the SubscriptionId field value if set, zero value otherwise.
func (o *FleetListAllInstanceSnapshotRequest) GetSubscriptionId() string {
	if o == nil || IsNil(o.SubscriptionId) {
		var ret string
		return ret
	}
	return *o.SubscriptionId
}

// GetSubscriptionIdOk returns a tuple with the SubscriptionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FleetListAllInstanceSnapshotRequest) GetSubscriptionIdOk() (*string, bool) {
	if o == nil || IsNil(o.SubscriptionId) {
		return nil, false
	}
	return o.SubscriptionId, true
}

// HasSubscriptionId returns a boolean if a field has been set.
func (o *FleetListAllInstanceSnapshotRequest) HasSubscriptionId() bool {
	if o != nil && !IsNil(o.SubscriptionId) {
		return true
	}

	return false
}

// SetSubscriptionId gets a reference to the given string and assigns it to the SubscriptionId field.
func (o *FleetListAllInstanceSnapshotRequest) SetSubscriptionId(v string) {
	o.SubscriptionId = &v
}

// GetToken returns the Token field value
func (o *FleetListAllInstanceSnapshotRequest) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *FleetListAllInstanceSnapshotRequest) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *FleetListAllInstanceSnapshotRequest) SetToken(v string) {
	o.Token = v
}

func (o FleetListAllInstanceSnapshotRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FleetListAllInstanceSnapshotRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["environmentId"] = o.EnvironmentId
	if !IsNil(o.ProductTierId) {
		toSerialize["productTierId"] = o.ProductTierId
	}
	toSerialize["serviceId"] = o.ServiceId
	if !IsNil(o.SnapshotType) {
		toSerialize["snapshotType"] = o.SnapshotType
	}
	if !IsNil(o.SubscriptionId) {
		toSerialize["subscriptionId"] = o.SubscriptionId
	}
	toSerialize["token"] = o.Token

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *FleetListAllInstanceSnapshotRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"environmentId",
		"serviceId",
		"token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFleetListAllInstanceSnapshotRequest := _FleetListAllInstanceSnapshotRequest{}

	err = json.Unmarshal(data, &varFleetListAllInstanceSnapshotRequest)

	if err != nil {
		return err
	}

	*o = FleetListAllInstanceSnapshotRequest(varFleetListAllInstanceSnapshotRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "environmentId")
		delete(additionalProperties, "productTierId")
		delete(additionalProperties, "serviceId")
		delete(additionalProperties, "snapshotType")
		delete(additionalProperties, "subscriptionId")
		delete(additionalProperties, "token")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableFleetListAllInstanceSnapshotRequest struct {
	value *FleetListAllInstanceSnapshotRequest
	isSet bool
}

func (v NullableFleetListAllInstanceSnapshotRequest) Get() *FleetListAllInstanceSnapshotRequest {
	return v.value
}

func (v *NullableFleetListAllInstanceSnapshotRequest) Set(val *FleetListAllInstanceSnapshotRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableFleetListAllInstanceSnapshotRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableFleetListAllInstanceSnapshotRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFleetListAllInstanceSnapshotRequest(val *FleetListAllInstanceSnapshotRequest) *NullableFleetListAllInstanceSnapshotRequest {
	return &NullableFleetListAllInstanceSnapshotRequest{value: val, isSet: true}
}

func (v NullableFleetListAllInstanceSnapshotRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFleetListAllInstanceSnapshotRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


