/*
Omnistrate Fleet API

REST API for Omnistrate Fleet

API version: 2022-09-01-00
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fleet

import (
	"encoding/json"
	"fmt"
)

// checks if the FleetDescribeEventRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FleetDescribeEventRequest{}

// FleetDescribeEventRequest struct for FleetDescribeEventRequest
type FleetDescribeEventRequest struct {
	// ID of a Service Environment
	EnvironmentId string `json:"environmentId"`
	// ID of a Event
	Id string `json:"id"`
	// ID of a Resource Instance
	InstanceId string `json:"instanceId"`
	// ID of a Service
	ServiceId string `json:"serviceId"`
	// JWT token used to perform authorization
	Token string `json:"token"`
	AdditionalProperties map[string]interface{}
}

type _FleetDescribeEventRequest FleetDescribeEventRequest

// NewFleetDescribeEventRequest instantiates a new FleetDescribeEventRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFleetDescribeEventRequest(environmentId string, id string, instanceId string, serviceId string, token string) *FleetDescribeEventRequest {
	this := FleetDescribeEventRequest{}
	this.EnvironmentId = environmentId
	this.Id = id
	this.InstanceId = instanceId
	this.ServiceId = serviceId
	this.Token = token
	return &this
}

// NewFleetDescribeEventRequestWithDefaults instantiates a new FleetDescribeEventRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFleetDescribeEventRequestWithDefaults() *FleetDescribeEventRequest {
	this := FleetDescribeEventRequest{}
	return &this
}

// GetEnvironmentId returns the EnvironmentId field value
func (o *FleetDescribeEventRequest) GetEnvironmentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EnvironmentId
}

// GetEnvironmentIdOk returns a tuple with the EnvironmentId field value
// and a boolean to check if the value has been set.
func (o *FleetDescribeEventRequest) GetEnvironmentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EnvironmentId, true
}

// SetEnvironmentId sets field value
func (o *FleetDescribeEventRequest) SetEnvironmentId(v string) {
	o.EnvironmentId = v
}

// GetId returns the Id field value
func (o *FleetDescribeEventRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *FleetDescribeEventRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *FleetDescribeEventRequest) SetId(v string) {
	o.Id = v
}

// GetInstanceId returns the InstanceId field value
func (o *FleetDescribeEventRequest) GetInstanceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.InstanceId
}

// GetInstanceIdOk returns a tuple with the InstanceId field value
// and a boolean to check if the value has been set.
func (o *FleetDescribeEventRequest) GetInstanceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InstanceId, true
}

// SetInstanceId sets field value
func (o *FleetDescribeEventRequest) SetInstanceId(v string) {
	o.InstanceId = v
}

// GetServiceId returns the ServiceId field value
func (o *FleetDescribeEventRequest) GetServiceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ServiceId
}

// GetServiceIdOk returns a tuple with the ServiceId field value
// and a boolean to check if the value has been set.
func (o *FleetDescribeEventRequest) GetServiceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceId, true
}

// SetServiceId sets field value
func (o *FleetDescribeEventRequest) SetServiceId(v string) {
	o.ServiceId = v
}

// GetToken returns the Token field value
func (o *FleetDescribeEventRequest) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *FleetDescribeEventRequest) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *FleetDescribeEventRequest) SetToken(v string) {
	o.Token = v
}

func (o FleetDescribeEventRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FleetDescribeEventRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["environmentId"] = o.EnvironmentId
	toSerialize["id"] = o.Id
	toSerialize["instanceId"] = o.InstanceId
	toSerialize["serviceId"] = o.ServiceId
	toSerialize["token"] = o.Token

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *FleetDescribeEventRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"environmentId",
		"id",
		"instanceId",
		"serviceId",
		"token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFleetDescribeEventRequest := _FleetDescribeEventRequest{}

	err = json.Unmarshal(data, &varFleetDescribeEventRequest)

	if err != nil {
		return err
	}

	*o = FleetDescribeEventRequest(varFleetDescribeEventRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "environmentId")
		delete(additionalProperties, "id")
		delete(additionalProperties, "instanceId")
		delete(additionalProperties, "serviceId")
		delete(additionalProperties, "token")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableFleetDescribeEventRequest struct {
	value *FleetDescribeEventRequest
	isSet bool
}

func (v NullableFleetDescribeEventRequest) Get() *FleetDescribeEventRequest {
	return v.value
}

func (v *NullableFleetDescribeEventRequest) Set(val *FleetDescribeEventRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableFleetDescribeEventRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableFleetDescribeEventRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFleetDescribeEventRequest(val *FleetDescribeEventRequest) *NullableFleetDescribeEventRequest {
	return &NullableFleetDescribeEventRequest{value: val, isSet: true}
}

func (v NullableFleetDescribeEventRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFleetDescribeEventRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


