/*
Omnistrate Fleet API

REST API for Omnistrate Fleet

API version: 2022-09-01-00
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fleet

import (
	"encoding/json"
)

// checks if the WorkflowTaskTerraformDetail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkflowTaskTerraformDetail{}

// WorkflowTaskTerraformDetail struct for WorkflowTaskTerraformDetail
type WorkflowTaskTerraformDetail struct {
	// The Terraform resource address that failed, when applicable.
	FailedAddress *string `json:"failedAddress,omitempty"`
	// The Terraform phase, e.g. plan, apply.
	Phase *string `json:"phase,omitempty"`
	// The number of resources to add in the current plan.
	PlanAdd *int64 `json:"planAdd,omitempty"`
	// The number of resources to change in the current plan.
	PlanChange *int64 `json:"planChange,omitempty"`
	// The number of resources to destroy in the current plan.
	PlanDestroy *int64 `json:"planDestroy,omitempty"`
	// Whether the Terraform state is currently locked.
	StateLocked *bool `json:"stateLocked,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _WorkflowTaskTerraformDetail WorkflowTaskTerraformDetail

// NewWorkflowTaskTerraformDetail instantiates a new WorkflowTaskTerraformDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkflowTaskTerraformDetail() *WorkflowTaskTerraformDetail {
	this := WorkflowTaskTerraformDetail{}
	return &this
}

// NewWorkflowTaskTerraformDetailWithDefaults instantiates a new WorkflowTaskTerraformDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkflowTaskTerraformDetailWithDefaults() *WorkflowTaskTerraformDetail {
	this := WorkflowTaskTerraformDetail{}
	return &this
}

// GetFailedAddress returns the FailedAddress field value if set, zero value otherwise.
func (o *WorkflowTaskTerraformDetail) GetFailedAddress() string {
	if o == nil || IsNil(o.FailedAddress) {
		var ret string
		return ret
	}
	return *o.FailedAddress
}

// GetFailedAddressOk returns a tuple with the FailedAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowTaskTerraformDetail) GetFailedAddressOk() (*string, bool) {
	if o == nil || IsNil(o.FailedAddress) {
		return nil, false
	}
	return o.FailedAddress, true
}

// HasFailedAddress returns a boolean if a field has been set.
func (o *WorkflowTaskTerraformDetail) HasFailedAddress() bool {
	if o != nil && !IsNil(o.FailedAddress) {
		return true
	}

	return false
}

// SetFailedAddress gets a reference to the given string and assigns it to the FailedAddress field.
func (o *WorkflowTaskTerraformDetail) SetFailedAddress(v string) {
	o.FailedAddress = &v
}

// GetPhase returns the Phase field value if set, zero value otherwise.
func (o *WorkflowTaskTerraformDetail) GetPhase() string {
	if o == nil || IsNil(o.Phase) {
		var ret string
		return ret
	}
	return *o.Phase
}

// GetPhaseOk returns a tuple with the Phase field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowTaskTerraformDetail) GetPhaseOk() (*string, bool) {
	if o == nil || IsNil(o.Phase) {
		return nil, false
	}
	return o.Phase, true
}

// HasPhase returns a boolean if a field has been set.
func (o *WorkflowTaskTerraformDetail) HasPhase() bool {
	if o != nil && !IsNil(o.Phase) {
		return true
	}

	return false
}

// SetPhase gets a reference to the given string and assigns it to the Phase field.
func (o *WorkflowTaskTerraformDetail) SetPhase(v string) {
	o.Phase = &v
}

// GetPlanAdd returns the PlanAdd field value if set, zero value otherwise.
func (o *WorkflowTaskTerraformDetail) GetPlanAdd() int64 {
	if o == nil || IsNil(o.PlanAdd) {
		var ret int64
		return ret
	}
	return *o.PlanAdd
}

// GetPlanAddOk returns a tuple with the PlanAdd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowTaskTerraformDetail) GetPlanAddOk() (*int64, bool) {
	if o == nil || IsNil(o.PlanAdd) {
		return nil, false
	}
	return o.PlanAdd, true
}

// HasPlanAdd returns a boolean if a field has been set.
func (o *WorkflowTaskTerraformDetail) HasPlanAdd() bool {
	if o != nil && !IsNil(o.PlanAdd) {
		return true
	}

	return false
}

// SetPlanAdd gets a reference to the given int64 and assigns it to the PlanAdd field.
func (o *WorkflowTaskTerraformDetail) SetPlanAdd(v int64) {
	o.PlanAdd = &v
}

// GetPlanChange returns the PlanChange field value if set, zero value otherwise.
func (o *WorkflowTaskTerraformDetail) GetPlanChange() int64 {
	if o == nil || IsNil(o.PlanChange) {
		var ret int64
		return ret
	}
	return *o.PlanChange
}

// GetPlanChangeOk returns a tuple with the PlanChange field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowTaskTerraformDetail) GetPlanChangeOk() (*int64, bool) {
	if o == nil || IsNil(o.PlanChange) {
		return nil, false
	}
	return o.PlanChange, true
}

// HasPlanChange returns a boolean if a field has been set.
func (o *WorkflowTaskTerraformDetail) HasPlanChange() bool {
	if o != nil && !IsNil(o.PlanChange) {
		return true
	}

	return false
}

// SetPlanChange gets a reference to the given int64 and assigns it to the PlanChange field.
func (o *WorkflowTaskTerraformDetail) SetPlanChange(v int64) {
	o.PlanChange = &v
}

// GetPlanDestroy returns the PlanDestroy field value if set, zero value otherwise.
func (o *WorkflowTaskTerraformDetail) GetPlanDestroy() int64 {
	if o == nil || IsNil(o.PlanDestroy) {
		var ret int64
		return ret
	}
	return *o.PlanDestroy
}

// GetPlanDestroyOk returns a tuple with the PlanDestroy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowTaskTerraformDetail) GetPlanDestroyOk() (*int64, bool) {
	if o == nil || IsNil(o.PlanDestroy) {
		return nil, false
	}
	return o.PlanDestroy, true
}

// HasPlanDestroy returns a boolean if a field has been set.
func (o *WorkflowTaskTerraformDetail) HasPlanDestroy() bool {
	if o != nil && !IsNil(o.PlanDestroy) {
		return true
	}

	return false
}

// SetPlanDestroy gets a reference to the given int64 and assigns it to the PlanDestroy field.
func (o *WorkflowTaskTerraformDetail) SetPlanDestroy(v int64) {
	o.PlanDestroy = &v
}

// GetStateLocked returns the StateLocked field value if set, zero value otherwise.
func (o *WorkflowTaskTerraformDetail) GetStateLocked() bool {
	if o == nil || IsNil(o.StateLocked) {
		var ret bool
		return ret
	}
	return *o.StateLocked
}

// GetStateLockedOk returns a tuple with the StateLocked field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowTaskTerraformDetail) GetStateLockedOk() (*bool, bool) {
	if o == nil || IsNil(o.StateLocked) {
		return nil, false
	}
	return o.StateLocked, true
}

// HasStateLocked returns a boolean if a field has been set.
func (o *WorkflowTaskTerraformDetail) HasStateLocked() bool {
	if o != nil && !IsNil(o.StateLocked) {
		return true
	}

	return false
}

// SetStateLocked gets a reference to the given bool and assigns it to the StateLocked field.
func (o *WorkflowTaskTerraformDetail) SetStateLocked(v bool) {
	o.StateLocked = &v
}

func (o WorkflowTaskTerraformDetail) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkflowTaskTerraformDetail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FailedAddress) {
		toSerialize["failedAddress"] = o.FailedAddress
	}
	if !IsNil(o.Phase) {
		toSerialize["phase"] = o.Phase
	}
	if !IsNil(o.PlanAdd) {
		toSerialize["planAdd"] = o.PlanAdd
	}
	if !IsNil(o.PlanChange) {
		toSerialize["planChange"] = o.PlanChange
	}
	if !IsNil(o.PlanDestroy) {
		toSerialize["planDestroy"] = o.PlanDestroy
	}
	if !IsNil(o.StateLocked) {
		toSerialize["stateLocked"] = o.StateLocked
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *WorkflowTaskTerraformDetail) UnmarshalJSON(data []byte) (err error) {
	varWorkflowTaskTerraformDetail := _WorkflowTaskTerraformDetail{}

	err = json.Unmarshal(data, &varWorkflowTaskTerraformDetail)

	if err != nil {
		return err
	}

	*o = WorkflowTaskTerraformDetail(varWorkflowTaskTerraformDetail)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "failedAddress")
		delete(additionalProperties, "phase")
		delete(additionalProperties, "planAdd")
		delete(additionalProperties, "planChange")
		delete(additionalProperties, "planDestroy")
		delete(additionalProperties, "stateLocked")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableWorkflowTaskTerraformDetail struct {
	value *WorkflowTaskTerraformDetail
	isSet bool
}

func (v NullableWorkflowTaskTerraformDetail) Get() *WorkflowTaskTerraformDetail {
	return v.value
}

func (v *NullableWorkflowTaskTerraformDetail) Set(val *WorkflowTaskTerraformDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowTaskTerraformDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowTaskTerraformDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowTaskTerraformDetail(val *WorkflowTaskTerraformDetail) *NullableWorkflowTaskTerraformDetail {
	return &NullableWorkflowTaskTerraformDetail{value: val, isSet: true}
}

func (v NullableWorkflowTaskTerraformDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowTaskTerraformDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


