/*
Omnistrate Fleet API

REST API for Omnistrate Fleet

API version: 2022-09-01-00
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fleet

import (
	"encoding/json"
	"time"
)

// checks if the ListDeploymentCellWorkflowsRequest2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListDeploymentCellWorkflowsRequest2{}

// ListDeploymentCellWorkflowsRequest2 struct for ListDeploymentCellWorkflowsRequest2
type ListDeploymentCellWorkflowsRequest2 struct {
	EndDate *time.Time `json:"endDate,omitempty"`
	NextPageToken *string `json:"nextPageToken,omitempty"`
	PageSize *int64 `json:"pageSize,omitempty"`
	StartDate *time.Time `json:"startDate,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListDeploymentCellWorkflowsRequest2 ListDeploymentCellWorkflowsRequest2

// NewListDeploymentCellWorkflowsRequest2 instantiates a new ListDeploymentCellWorkflowsRequest2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListDeploymentCellWorkflowsRequest2() *ListDeploymentCellWorkflowsRequest2 {
	this := ListDeploymentCellWorkflowsRequest2{}
	return &this
}

// NewListDeploymentCellWorkflowsRequest2WithDefaults instantiates a new ListDeploymentCellWorkflowsRequest2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListDeploymentCellWorkflowsRequest2WithDefaults() *ListDeploymentCellWorkflowsRequest2 {
	this := ListDeploymentCellWorkflowsRequest2{}
	return &this
}

// GetEndDate returns the EndDate field value if set, zero value otherwise.
func (o *ListDeploymentCellWorkflowsRequest2) GetEndDate() time.Time {
	if o == nil || IsNil(o.EndDate) {
		var ret time.Time
		return ret
	}
	return *o.EndDate
}

// GetEndDateOk returns a tuple with the EndDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListDeploymentCellWorkflowsRequest2) GetEndDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.EndDate) {
		return nil, false
	}
	return o.EndDate, true
}

// HasEndDate returns a boolean if a field has been set.
func (o *ListDeploymentCellWorkflowsRequest2) HasEndDate() bool {
	if o != nil && !IsNil(o.EndDate) {
		return true
	}

	return false
}

// SetEndDate gets a reference to the given time.Time and assigns it to the EndDate field.
func (o *ListDeploymentCellWorkflowsRequest2) SetEndDate(v time.Time) {
	o.EndDate = &v
}

// GetNextPageToken returns the NextPageToken field value if set, zero value otherwise.
func (o *ListDeploymentCellWorkflowsRequest2) GetNextPageToken() string {
	if o == nil || IsNil(o.NextPageToken) {
		var ret string
		return ret
	}
	return *o.NextPageToken
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListDeploymentCellWorkflowsRequest2) GetNextPageTokenOk() (*string, bool) {
	if o == nil || IsNil(o.NextPageToken) {
		return nil, false
	}
	return o.NextPageToken, true
}

// HasNextPageToken returns a boolean if a field has been set.
func (o *ListDeploymentCellWorkflowsRequest2) HasNextPageToken() bool {
	if o != nil && !IsNil(o.NextPageToken) {
		return true
	}

	return false
}

// SetNextPageToken gets a reference to the given string and assigns it to the NextPageToken field.
func (o *ListDeploymentCellWorkflowsRequest2) SetNextPageToken(v string) {
	o.NextPageToken = &v
}

// GetPageSize returns the PageSize field value if set, zero value otherwise.
func (o *ListDeploymentCellWorkflowsRequest2) GetPageSize() int64 {
	if o == nil || IsNil(o.PageSize) {
		var ret int64
		return ret
	}
	return *o.PageSize
}

// GetPageSizeOk returns a tuple with the PageSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListDeploymentCellWorkflowsRequest2) GetPageSizeOk() (*int64, bool) {
	if o == nil || IsNil(o.PageSize) {
		return nil, false
	}
	return o.PageSize, true
}

// HasPageSize returns a boolean if a field has been set.
func (o *ListDeploymentCellWorkflowsRequest2) HasPageSize() bool {
	if o != nil && !IsNil(o.PageSize) {
		return true
	}

	return false
}

// SetPageSize gets a reference to the given int64 and assigns it to the PageSize field.
func (o *ListDeploymentCellWorkflowsRequest2) SetPageSize(v int64) {
	o.PageSize = &v
}

// GetStartDate returns the StartDate field value if set, zero value otherwise.
func (o *ListDeploymentCellWorkflowsRequest2) GetStartDate() time.Time {
	if o == nil || IsNil(o.StartDate) {
		var ret time.Time
		return ret
	}
	return *o.StartDate
}

// GetStartDateOk returns a tuple with the StartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListDeploymentCellWorkflowsRequest2) GetStartDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.StartDate) {
		return nil, false
	}
	return o.StartDate, true
}

// HasStartDate returns a boolean if a field has been set.
func (o *ListDeploymentCellWorkflowsRequest2) HasStartDate() bool {
	if o != nil && !IsNil(o.StartDate) {
		return true
	}

	return false
}

// SetStartDate gets a reference to the given time.Time and assigns it to the StartDate field.
func (o *ListDeploymentCellWorkflowsRequest2) SetStartDate(v time.Time) {
	o.StartDate = &v
}

func (o ListDeploymentCellWorkflowsRequest2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListDeploymentCellWorkflowsRequest2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EndDate) {
		toSerialize["endDate"] = o.EndDate
	}
	if !IsNil(o.NextPageToken) {
		toSerialize["nextPageToken"] = o.NextPageToken
	}
	if !IsNil(o.PageSize) {
		toSerialize["pageSize"] = o.PageSize
	}
	if !IsNil(o.StartDate) {
		toSerialize["startDate"] = o.StartDate
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListDeploymentCellWorkflowsRequest2) UnmarshalJSON(data []byte) (err error) {
	varListDeploymentCellWorkflowsRequest2 := _ListDeploymentCellWorkflowsRequest2{}

	err = json.Unmarshal(data, &varListDeploymentCellWorkflowsRequest2)

	if err != nil {
		return err
	}

	*o = ListDeploymentCellWorkflowsRequest2(varListDeploymentCellWorkflowsRequest2)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "endDate")
		delete(additionalProperties, "nextPageToken")
		delete(additionalProperties, "pageSize")
		delete(additionalProperties, "startDate")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListDeploymentCellWorkflowsRequest2 struct {
	value *ListDeploymentCellWorkflowsRequest2
	isSet bool
}

func (v NullableListDeploymentCellWorkflowsRequest2) Get() *ListDeploymentCellWorkflowsRequest2 {
	return v.value
}

func (v *NullableListDeploymentCellWorkflowsRequest2) Set(val *ListDeploymentCellWorkflowsRequest2) {
	v.value = val
	v.isSet = true
}

func (v NullableListDeploymentCellWorkflowsRequest2) IsSet() bool {
	return v.isSet
}

func (v *NullableListDeploymentCellWorkflowsRequest2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListDeploymentCellWorkflowsRequest2(val *ListDeploymentCellWorkflowsRequest2) *NullableListDeploymentCellWorkflowsRequest2 {
	return &NullableListDeploymentCellWorkflowsRequest2{value: val, isSet: true}
}

func (v NullableListDeploymentCellWorkflowsRequest2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListDeploymentCellWorkflowsRequest2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


