/*
Omnistrate Fleet API

REST API for Omnistrate Fleet

API version: 2022-09-01-00
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fleet

import (
	"encoding/json"
	"fmt"
)

// checks if the FleetResendInvoiceRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FleetResendInvoiceRequest{}

// FleetResendInvoiceRequest struct for FleetResendInvoiceRequest
type FleetResendInvoiceRequest struct {
	// ID of the invoice
	Id string `json:"id"`
	// JWT token used to perform authorization
	Token string `json:"token"`
	AdditionalProperties map[string]interface{}
}

type _FleetResendInvoiceRequest FleetResendInvoiceRequest

// NewFleetResendInvoiceRequest instantiates a new FleetResendInvoiceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFleetResendInvoiceRequest(id string, token string) *FleetResendInvoiceRequest {
	this := FleetResendInvoiceRequest{}
	this.Id = id
	this.Token = token
	return &this
}

// NewFleetResendInvoiceRequestWithDefaults instantiates a new FleetResendInvoiceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFleetResendInvoiceRequestWithDefaults() *FleetResendInvoiceRequest {
	this := FleetResendInvoiceRequest{}
	return &this
}

// GetId returns the Id field value
func (o *FleetResendInvoiceRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *FleetResendInvoiceRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *FleetResendInvoiceRequest) SetId(v string) {
	o.Id = v
}

// GetToken returns the Token field value
func (o *FleetResendInvoiceRequest) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *FleetResendInvoiceRequest) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *FleetResendInvoiceRequest) SetToken(v string) {
	o.Token = v
}

func (o FleetResendInvoiceRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FleetResendInvoiceRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["token"] = o.Token

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *FleetResendInvoiceRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFleetResendInvoiceRequest := _FleetResendInvoiceRequest{}

	err = json.Unmarshal(data, &varFleetResendInvoiceRequest)

	if err != nil {
		return err
	}

	*o = FleetResendInvoiceRequest(varFleetResendInvoiceRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "token")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableFleetResendInvoiceRequest struct {
	value *FleetResendInvoiceRequest
	isSet bool
}

func (v NullableFleetResendInvoiceRequest) Get() *FleetResendInvoiceRequest {
	return v.value
}

func (v *NullableFleetResendInvoiceRequest) Set(val *FleetResendInvoiceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableFleetResendInvoiceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableFleetResendInvoiceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFleetResendInvoiceRequest(val *FleetResendInvoiceRequest) *NullableFleetResendInvoiceRequest {
	return &NullableFleetResendInvoiceRequest{value: val, isSet: true}
}

func (v NullableFleetResendInvoiceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFleetResendInvoiceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


