/*
Omnistrate Fleet API

REST API for Omnistrate Fleet

API version: 2022-09-01-00
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fleet

import (
	"encoding/json"
	"fmt"
)

// checks if the FleetCreateInvoiceRequest2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FleetCreateInvoiceRequest2{}

// FleetCreateInvoiceRequest2 struct for FleetCreateInvoiceRequest2
type FleetCreateInvoiceRequest2 struct {
	// Billing month to invoice in YYYY-MM format
	BillingPeriod string `json:"billingPeriod"`
	// Organization ID of the customer to invoice
	CustomerId string `json:"customerId"`
	AdditionalProperties map[string]interface{}
}

type _FleetCreateInvoiceRequest2 FleetCreateInvoiceRequest2

// NewFleetCreateInvoiceRequest2 instantiates a new FleetCreateInvoiceRequest2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFleetCreateInvoiceRequest2(billingPeriod string, customerId string) *FleetCreateInvoiceRequest2 {
	this := FleetCreateInvoiceRequest2{}
	this.BillingPeriod = billingPeriod
	this.CustomerId = customerId
	return &this
}

// NewFleetCreateInvoiceRequest2WithDefaults instantiates a new FleetCreateInvoiceRequest2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFleetCreateInvoiceRequest2WithDefaults() *FleetCreateInvoiceRequest2 {
	this := FleetCreateInvoiceRequest2{}
	return &this
}

// GetBillingPeriod returns the BillingPeriod field value
func (o *FleetCreateInvoiceRequest2) GetBillingPeriod() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BillingPeriod
}

// GetBillingPeriodOk returns a tuple with the BillingPeriod field value
// and a boolean to check if the value has been set.
func (o *FleetCreateInvoiceRequest2) GetBillingPeriodOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BillingPeriod, true
}

// SetBillingPeriod sets field value
func (o *FleetCreateInvoiceRequest2) SetBillingPeriod(v string) {
	o.BillingPeriod = v
}

// GetCustomerId returns the CustomerId field value
func (o *FleetCreateInvoiceRequest2) GetCustomerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CustomerId
}

// GetCustomerIdOk returns a tuple with the CustomerId field value
// and a boolean to check if the value has been set.
func (o *FleetCreateInvoiceRequest2) GetCustomerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CustomerId, true
}

// SetCustomerId sets field value
func (o *FleetCreateInvoiceRequest2) SetCustomerId(v string) {
	o.CustomerId = v
}

func (o FleetCreateInvoiceRequest2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FleetCreateInvoiceRequest2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["billingPeriod"] = o.BillingPeriod
	toSerialize["customerId"] = o.CustomerId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *FleetCreateInvoiceRequest2) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"billingPeriod",
		"customerId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFleetCreateInvoiceRequest2 := _FleetCreateInvoiceRequest2{}

	err = json.Unmarshal(data, &varFleetCreateInvoiceRequest2)

	if err != nil {
		return err
	}

	*o = FleetCreateInvoiceRequest2(varFleetCreateInvoiceRequest2)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "billingPeriod")
		delete(additionalProperties, "customerId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableFleetCreateInvoiceRequest2 struct {
	value *FleetCreateInvoiceRequest2
	isSet bool
}

func (v NullableFleetCreateInvoiceRequest2) Get() *FleetCreateInvoiceRequest2 {
	return v.value
}

func (v *NullableFleetCreateInvoiceRequest2) Set(val *FleetCreateInvoiceRequest2) {
	v.value = val
	v.isSet = true
}

func (v NullableFleetCreateInvoiceRequest2) IsSet() bool {
	return v.isSet
}

func (v *NullableFleetCreateInvoiceRequest2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFleetCreateInvoiceRequest2(val *FleetCreateInvoiceRequest2) *NullableFleetCreateInvoiceRequest2 {
	return &NullableFleetCreateInvoiceRequest2{value: val, isSet: true}
}

func (v NullableFleetCreateInvoiceRequest2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFleetCreateInvoiceRequest2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


