/*
Omnistrate Fleet API

REST API for Omnistrate Fleet

API version: 2022-09-01-00
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fleet

import (
	"encoding/json"
)

// checks if the FleetRestoreResourceInstanceFromSnapshotRequest2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FleetRestoreResourceInstanceFromSnapshotRequest2{}

// FleetRestoreResourceInstanceFromSnapshotRequest2 struct for FleetRestoreResourceInstanceFromSnapshotRequest2
type FleetRestoreResourceInstanceFromSnapshotRequest2 struct {
	// Custom input parameters override
	InputParametersOverride interface{} `json:"inputParametersOverride,omitempty"`
	// The network type
	NetworkType *string `json:"network_type,omitempty"`
	// The product tier version
	ProductTierVersionOverride *string `json:"productTierVersionOverride,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _FleetRestoreResourceInstanceFromSnapshotRequest2 FleetRestoreResourceInstanceFromSnapshotRequest2

// NewFleetRestoreResourceInstanceFromSnapshotRequest2 instantiates a new FleetRestoreResourceInstanceFromSnapshotRequest2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFleetRestoreResourceInstanceFromSnapshotRequest2() *FleetRestoreResourceInstanceFromSnapshotRequest2 {
	this := FleetRestoreResourceInstanceFromSnapshotRequest2{}
	return &this
}

// NewFleetRestoreResourceInstanceFromSnapshotRequest2WithDefaults instantiates a new FleetRestoreResourceInstanceFromSnapshotRequest2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFleetRestoreResourceInstanceFromSnapshotRequest2WithDefaults() *FleetRestoreResourceInstanceFromSnapshotRequest2 {
	this := FleetRestoreResourceInstanceFromSnapshotRequest2{}
	return &this
}

// GetInputParametersOverride returns the InputParametersOverride field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FleetRestoreResourceInstanceFromSnapshotRequest2) GetInputParametersOverride() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.InputParametersOverride
}

// GetInputParametersOverrideOk returns a tuple with the InputParametersOverride field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FleetRestoreResourceInstanceFromSnapshotRequest2) GetInputParametersOverrideOk() (*interface{}, bool) {
	if o == nil || IsNil(o.InputParametersOverride) {
		return nil, false
	}
	return &o.InputParametersOverride, true
}

// HasInputParametersOverride returns a boolean if a field has been set.
func (o *FleetRestoreResourceInstanceFromSnapshotRequest2) HasInputParametersOverride() bool {
	if o != nil && !IsNil(o.InputParametersOverride) {
		return true
	}

	return false
}

// SetInputParametersOverride gets a reference to the given interface{} and assigns it to the InputParametersOverride field.
func (o *FleetRestoreResourceInstanceFromSnapshotRequest2) SetInputParametersOverride(v interface{}) {
	o.InputParametersOverride = v
}

// GetNetworkType returns the NetworkType field value if set, zero value otherwise.
func (o *FleetRestoreResourceInstanceFromSnapshotRequest2) GetNetworkType() string {
	if o == nil || IsNil(o.NetworkType) {
		var ret string
		return ret
	}
	return *o.NetworkType
}

// GetNetworkTypeOk returns a tuple with the NetworkType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FleetRestoreResourceInstanceFromSnapshotRequest2) GetNetworkTypeOk() (*string, bool) {
	if o == nil || IsNil(o.NetworkType) {
		return nil, false
	}
	return o.NetworkType, true
}

// HasNetworkType returns a boolean if a field has been set.
func (o *FleetRestoreResourceInstanceFromSnapshotRequest2) HasNetworkType() bool {
	if o != nil && !IsNil(o.NetworkType) {
		return true
	}

	return false
}

// SetNetworkType gets a reference to the given string and assigns it to the NetworkType field.
func (o *FleetRestoreResourceInstanceFromSnapshotRequest2) SetNetworkType(v string) {
	o.NetworkType = &v
}

// GetProductTierVersionOverride returns the ProductTierVersionOverride field value if set, zero value otherwise.
func (o *FleetRestoreResourceInstanceFromSnapshotRequest2) GetProductTierVersionOverride() string {
	if o == nil || IsNil(o.ProductTierVersionOverride) {
		var ret string
		return ret
	}
	return *o.ProductTierVersionOverride
}

// GetProductTierVersionOverrideOk returns a tuple with the ProductTierVersionOverride field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FleetRestoreResourceInstanceFromSnapshotRequest2) GetProductTierVersionOverrideOk() (*string, bool) {
	if o == nil || IsNil(o.ProductTierVersionOverride) {
		return nil, false
	}
	return o.ProductTierVersionOverride, true
}

// HasProductTierVersionOverride returns a boolean if a field has been set.
func (o *FleetRestoreResourceInstanceFromSnapshotRequest2) HasProductTierVersionOverride() bool {
	if o != nil && !IsNil(o.ProductTierVersionOverride) {
		return true
	}

	return false
}

// SetProductTierVersionOverride gets a reference to the given string and assigns it to the ProductTierVersionOverride field.
func (o *FleetRestoreResourceInstanceFromSnapshotRequest2) SetProductTierVersionOverride(v string) {
	o.ProductTierVersionOverride = &v
}

func (o FleetRestoreResourceInstanceFromSnapshotRequest2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FleetRestoreResourceInstanceFromSnapshotRequest2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.InputParametersOverride != nil {
		toSerialize["inputParametersOverride"] = o.InputParametersOverride
	}
	if !IsNil(o.NetworkType) {
		toSerialize["network_type"] = o.NetworkType
	}
	if !IsNil(o.ProductTierVersionOverride) {
		toSerialize["productTierVersionOverride"] = o.ProductTierVersionOverride
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *FleetRestoreResourceInstanceFromSnapshotRequest2) UnmarshalJSON(data []byte) (err error) {
	varFleetRestoreResourceInstanceFromSnapshotRequest2 := _FleetRestoreResourceInstanceFromSnapshotRequest2{}

	err = json.Unmarshal(data, &varFleetRestoreResourceInstanceFromSnapshotRequest2)

	if err != nil {
		return err
	}

	*o = FleetRestoreResourceInstanceFromSnapshotRequest2(varFleetRestoreResourceInstanceFromSnapshotRequest2)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "inputParametersOverride")
		delete(additionalProperties, "network_type")
		delete(additionalProperties, "productTierVersionOverride")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableFleetRestoreResourceInstanceFromSnapshotRequest2 struct {
	value *FleetRestoreResourceInstanceFromSnapshotRequest2
	isSet bool
}

func (v NullableFleetRestoreResourceInstanceFromSnapshotRequest2) Get() *FleetRestoreResourceInstanceFromSnapshotRequest2 {
	return v.value
}

func (v *NullableFleetRestoreResourceInstanceFromSnapshotRequest2) Set(val *FleetRestoreResourceInstanceFromSnapshotRequest2) {
	v.value = val
	v.isSet = true
}

func (v NullableFleetRestoreResourceInstanceFromSnapshotRequest2) IsSet() bool {
	return v.isSet
}

func (v *NullableFleetRestoreResourceInstanceFromSnapshotRequest2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFleetRestoreResourceInstanceFromSnapshotRequest2(val *FleetRestoreResourceInstanceFromSnapshotRequest2) *NullableFleetRestoreResourceInstanceFromSnapshotRequest2 {
	return &NullableFleetRestoreResourceInstanceFromSnapshotRequest2{value: val, isSet: true}
}

func (v NullableFleetRestoreResourceInstanceFromSnapshotRequest2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFleetRestoreResourceInstanceFromSnapshotRequest2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


