/*
Omnistrate Fleet API

REST API for Omnistrate Fleet

API version: 2022-09-01-00
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fleet

import (
	"encoding/json"
)

// checks if the AdoptResourceInstanceRequest2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdoptResourceInstanceRequest2{}

// AdoptResourceInstanceRequest2 struct for AdoptResourceInstanceRequest2
type AdoptResourceInstanceRequest2 struct {
	// The cloud provider name
	CloudProvider *string `json:"cloud_provider,omitempty"`
	// Custom network for resource
	CustomNetworkId *string `json:"custom_network_id,omitempty"`
	// The external payer id to record which customer should pay for this resource instance. This will override the subscription level external payer id if set.
	ExternalPayerId *string `json:"externalPayerId,omitempty"`
	// The product tier version
	ProductTierVersion *string `json:"productTierVersion,omitempty"`
	// The region code
	Region *string `json:"region,omitempty"`
	// The resource configuration
	ResourceConfiguration map[string]interface{} `json:"resourceConfiguration,omitempty"`
	// The subscription ID
	SubscriptionId *string `json:"subscriptionId,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AdoptResourceInstanceRequest2 AdoptResourceInstanceRequest2

// NewAdoptResourceInstanceRequest2 instantiates a new AdoptResourceInstanceRequest2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdoptResourceInstanceRequest2() *AdoptResourceInstanceRequest2 {
	this := AdoptResourceInstanceRequest2{}
	return &this
}

// NewAdoptResourceInstanceRequest2WithDefaults instantiates a new AdoptResourceInstanceRequest2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdoptResourceInstanceRequest2WithDefaults() *AdoptResourceInstanceRequest2 {
	this := AdoptResourceInstanceRequest2{}
	return &this
}

// GetCloudProvider returns the CloudProvider field value if set, zero value otherwise.
func (o *AdoptResourceInstanceRequest2) GetCloudProvider() string {
	if o == nil || IsNil(o.CloudProvider) {
		var ret string
		return ret
	}
	return *o.CloudProvider
}

// GetCloudProviderOk returns a tuple with the CloudProvider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdoptResourceInstanceRequest2) GetCloudProviderOk() (*string, bool) {
	if o == nil || IsNil(o.CloudProvider) {
		return nil, false
	}
	return o.CloudProvider, true
}

// HasCloudProvider returns a boolean if a field has been set.
func (o *AdoptResourceInstanceRequest2) HasCloudProvider() bool {
	if o != nil && !IsNil(o.CloudProvider) {
		return true
	}

	return false
}

// SetCloudProvider gets a reference to the given string and assigns it to the CloudProvider field.
func (o *AdoptResourceInstanceRequest2) SetCloudProvider(v string) {
	o.CloudProvider = &v
}

// GetCustomNetworkId returns the CustomNetworkId field value if set, zero value otherwise.
func (o *AdoptResourceInstanceRequest2) GetCustomNetworkId() string {
	if o == nil || IsNil(o.CustomNetworkId) {
		var ret string
		return ret
	}
	return *o.CustomNetworkId
}

// GetCustomNetworkIdOk returns a tuple with the CustomNetworkId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdoptResourceInstanceRequest2) GetCustomNetworkIdOk() (*string, bool) {
	if o == nil || IsNil(o.CustomNetworkId) {
		return nil, false
	}
	return o.CustomNetworkId, true
}

// HasCustomNetworkId returns a boolean if a field has been set.
func (o *AdoptResourceInstanceRequest2) HasCustomNetworkId() bool {
	if o != nil && !IsNil(o.CustomNetworkId) {
		return true
	}

	return false
}

// SetCustomNetworkId gets a reference to the given string and assigns it to the CustomNetworkId field.
func (o *AdoptResourceInstanceRequest2) SetCustomNetworkId(v string) {
	o.CustomNetworkId = &v
}

// GetExternalPayerId returns the ExternalPayerId field value if set, zero value otherwise.
func (o *AdoptResourceInstanceRequest2) GetExternalPayerId() string {
	if o == nil || IsNil(o.ExternalPayerId) {
		var ret string
		return ret
	}
	return *o.ExternalPayerId
}

// GetExternalPayerIdOk returns a tuple with the ExternalPayerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdoptResourceInstanceRequest2) GetExternalPayerIdOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalPayerId) {
		return nil, false
	}
	return o.ExternalPayerId, true
}

// HasExternalPayerId returns a boolean if a field has been set.
func (o *AdoptResourceInstanceRequest2) HasExternalPayerId() bool {
	if o != nil && !IsNil(o.ExternalPayerId) {
		return true
	}

	return false
}

// SetExternalPayerId gets a reference to the given string and assigns it to the ExternalPayerId field.
func (o *AdoptResourceInstanceRequest2) SetExternalPayerId(v string) {
	o.ExternalPayerId = &v
}

// GetProductTierVersion returns the ProductTierVersion field value if set, zero value otherwise.
func (o *AdoptResourceInstanceRequest2) GetProductTierVersion() string {
	if o == nil || IsNil(o.ProductTierVersion) {
		var ret string
		return ret
	}
	return *o.ProductTierVersion
}

// GetProductTierVersionOk returns a tuple with the ProductTierVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdoptResourceInstanceRequest2) GetProductTierVersionOk() (*string, bool) {
	if o == nil || IsNil(o.ProductTierVersion) {
		return nil, false
	}
	return o.ProductTierVersion, true
}

// HasProductTierVersion returns a boolean if a field has been set.
func (o *AdoptResourceInstanceRequest2) HasProductTierVersion() bool {
	if o != nil && !IsNil(o.ProductTierVersion) {
		return true
	}

	return false
}

// SetProductTierVersion gets a reference to the given string and assigns it to the ProductTierVersion field.
func (o *AdoptResourceInstanceRequest2) SetProductTierVersion(v string) {
	o.ProductTierVersion = &v
}

// GetRegion returns the Region field value if set, zero value otherwise.
func (o *AdoptResourceInstanceRequest2) GetRegion() string {
	if o == nil || IsNil(o.Region) {
		var ret string
		return ret
	}
	return *o.Region
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdoptResourceInstanceRequest2) GetRegionOk() (*string, bool) {
	if o == nil || IsNil(o.Region) {
		return nil, false
	}
	return o.Region, true
}

// HasRegion returns a boolean if a field has been set.
func (o *AdoptResourceInstanceRequest2) HasRegion() bool {
	if o != nil && !IsNil(o.Region) {
		return true
	}

	return false
}

// SetRegion gets a reference to the given string and assigns it to the Region field.
func (o *AdoptResourceInstanceRequest2) SetRegion(v string) {
	o.Region = &v
}

// GetResourceConfiguration returns the ResourceConfiguration field value if set, zero value otherwise.
func (o *AdoptResourceInstanceRequest2) GetResourceConfiguration() map[string]interface{} {
	if o == nil || IsNil(o.ResourceConfiguration) {
		var ret map[string]interface{}
		return ret
	}
	return o.ResourceConfiguration
}

// GetResourceConfigurationOk returns a tuple with the ResourceConfiguration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdoptResourceInstanceRequest2) GetResourceConfigurationOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.ResourceConfiguration) {
		return map[string]interface{}{}, false
	}
	return o.ResourceConfiguration, true
}

// HasResourceConfiguration returns a boolean if a field has been set.
func (o *AdoptResourceInstanceRequest2) HasResourceConfiguration() bool {
	if o != nil && !IsNil(o.ResourceConfiguration) {
		return true
	}

	return false
}

// SetResourceConfiguration gets a reference to the given map[string]interface{} and assigns it to the ResourceConfiguration field.
func (o *AdoptResourceInstanceRequest2) SetResourceConfiguration(v map[string]interface{}) {
	o.ResourceConfiguration = v
}

// GetSubscriptionId returns the SubscriptionId field value if set, zero value otherwise.
func (o *AdoptResourceInstanceRequest2) GetSubscriptionId() string {
	if o == nil || IsNil(o.SubscriptionId) {
		var ret string
		return ret
	}
	return *o.SubscriptionId
}

// GetSubscriptionIdOk returns a tuple with the SubscriptionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdoptResourceInstanceRequest2) GetSubscriptionIdOk() (*string, bool) {
	if o == nil || IsNil(o.SubscriptionId) {
		return nil, false
	}
	return o.SubscriptionId, true
}

// HasSubscriptionId returns a boolean if a field has been set.
func (o *AdoptResourceInstanceRequest2) HasSubscriptionId() bool {
	if o != nil && !IsNil(o.SubscriptionId) {
		return true
	}

	return false
}

// SetSubscriptionId gets a reference to the given string and assigns it to the SubscriptionId field.
func (o *AdoptResourceInstanceRequest2) SetSubscriptionId(v string) {
	o.SubscriptionId = &v
}

func (o AdoptResourceInstanceRequest2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdoptResourceInstanceRequest2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CloudProvider) {
		toSerialize["cloud_provider"] = o.CloudProvider
	}
	if !IsNil(o.CustomNetworkId) {
		toSerialize["custom_network_id"] = o.CustomNetworkId
	}
	if !IsNil(o.ExternalPayerId) {
		toSerialize["externalPayerId"] = o.ExternalPayerId
	}
	if !IsNil(o.ProductTierVersion) {
		toSerialize["productTierVersion"] = o.ProductTierVersion
	}
	if !IsNil(o.Region) {
		toSerialize["region"] = o.Region
	}
	if !IsNil(o.ResourceConfiguration) {
		toSerialize["resourceConfiguration"] = o.ResourceConfiguration
	}
	if !IsNil(o.SubscriptionId) {
		toSerialize["subscriptionId"] = o.SubscriptionId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AdoptResourceInstanceRequest2) UnmarshalJSON(data []byte) (err error) {
	varAdoptResourceInstanceRequest2 := _AdoptResourceInstanceRequest2{}

	err = json.Unmarshal(data, &varAdoptResourceInstanceRequest2)

	if err != nil {
		return err
	}

	*o = AdoptResourceInstanceRequest2(varAdoptResourceInstanceRequest2)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "cloud_provider")
		delete(additionalProperties, "custom_network_id")
		delete(additionalProperties, "externalPayerId")
		delete(additionalProperties, "productTierVersion")
		delete(additionalProperties, "region")
		delete(additionalProperties, "resourceConfiguration")
		delete(additionalProperties, "subscriptionId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAdoptResourceInstanceRequest2 struct {
	value *AdoptResourceInstanceRequest2
	isSet bool
}

func (v NullableAdoptResourceInstanceRequest2) Get() *AdoptResourceInstanceRequest2 {
	return v.value
}

func (v *NullableAdoptResourceInstanceRequest2) Set(val *AdoptResourceInstanceRequest2) {
	v.value = val
	v.isSet = true
}

func (v NullableAdoptResourceInstanceRequest2) IsSet() bool {
	return v.isSet
}

func (v *NullableAdoptResourceInstanceRequest2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdoptResourceInstanceRequest2(val *AdoptResourceInstanceRequest2) *NullableAdoptResourceInstanceRequest2 {
	return &NullableAdoptResourceInstanceRequest2{value: val, isSet: true}
}

func (v NullableAdoptResourceInstanceRequest2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdoptResourceInstanceRequest2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


