/*
Omnistrate Fleet API

REST API for Omnistrate Fleet

API version: 2022-09-01-00
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fleet

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the HelmPackage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HelmPackage{}

// HelmPackage struct for HelmPackage
type HelmPackage struct {
	// The chart name of the Helm package
	ChartName string `json:"chartName"`
	// The chart version of the Helm package
	ChartVersion string `json:"chartVersion"`
	// The namespace where the Helm package is installed
	Namespace string `json:"namespace"`
	// The repository URL of the Helm package
	RepoURL string `json:"repoURL"`
	// Custom values for the helm package
	Values map[string]interface{} `json:"values,omitempty"`
}

type _HelmPackage HelmPackage

// NewHelmPackage instantiates a new HelmPackage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHelmPackage(chartName string, chartVersion string, namespace string, repoURL string) *HelmPackage {
	this := HelmPackage{}
	this.ChartName = chartName
	this.ChartVersion = chartVersion
	this.Namespace = namespace
	this.RepoURL = repoURL
	return &this
}

// NewHelmPackageWithDefaults instantiates a new HelmPackage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHelmPackageWithDefaults() *HelmPackage {
	this := HelmPackage{}
	return &this
}

// GetChartName returns the ChartName field value
func (o *HelmPackage) GetChartName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChartName
}

// GetChartNameOk returns a tuple with the ChartName field value
// and a boolean to check if the value has been set.
func (o *HelmPackage) GetChartNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChartName, true
}

// SetChartName sets field value
func (o *HelmPackage) SetChartName(v string) {
	o.ChartName = v
}

// GetChartVersion returns the ChartVersion field value
func (o *HelmPackage) GetChartVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChartVersion
}

// GetChartVersionOk returns a tuple with the ChartVersion field value
// and a boolean to check if the value has been set.
func (o *HelmPackage) GetChartVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChartVersion, true
}

// SetChartVersion sets field value
func (o *HelmPackage) SetChartVersion(v string) {
	o.ChartVersion = v
}

// GetNamespace returns the Namespace field value
func (o *HelmPackage) GetNamespace() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value
// and a boolean to check if the value has been set.
func (o *HelmPackage) GetNamespaceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Namespace, true
}

// SetNamespace sets field value
func (o *HelmPackage) SetNamespace(v string) {
	o.Namespace = v
}

// GetRepoURL returns the RepoURL field value
func (o *HelmPackage) GetRepoURL() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RepoURL
}

// GetRepoURLOk returns a tuple with the RepoURL field value
// and a boolean to check if the value has been set.
func (o *HelmPackage) GetRepoURLOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RepoURL, true
}

// SetRepoURL sets field value
func (o *HelmPackage) SetRepoURL(v string) {
	o.RepoURL = v
}

// GetValues returns the Values field value if set, zero value otherwise.
func (o *HelmPackage) GetValues() map[string]interface{} {
	if o == nil || IsNil(o.Values) {
		var ret map[string]interface{}
		return ret
	}
	return o.Values
}

// GetValuesOk returns a tuple with the Values field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HelmPackage) GetValuesOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Values) {
		return map[string]interface{}{}, false
	}
	return o.Values, true
}

// HasValues returns a boolean if a field has been set.
func (o *HelmPackage) HasValues() bool {
	if o != nil && !IsNil(o.Values) {
		return true
	}

	return false
}

// SetValues gets a reference to the given map[string]interface{} and assigns it to the Values field.
func (o *HelmPackage) SetValues(v map[string]interface{}) {
	o.Values = v
}

func (o HelmPackage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HelmPackage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["chartName"] = o.ChartName
	toSerialize["chartVersion"] = o.ChartVersion
	toSerialize["namespace"] = o.Namespace
	toSerialize["repoURL"] = o.RepoURL
	if !IsNil(o.Values) {
		toSerialize["values"] = o.Values
	}
	return toSerialize, nil
}

func (o *HelmPackage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"chartName",
		"chartVersion",
		"namespace",
		"repoURL",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHelmPackage := _HelmPackage{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHelmPackage)

	if err != nil {
		return err
	}

	*o = HelmPackage(varHelmPackage)

	return err
}

type NullableHelmPackage struct {
	value *HelmPackage
	isSet bool
}

func (v NullableHelmPackage) Get() *HelmPackage {
	return v.value
}

func (v *NullableHelmPackage) Set(val *HelmPackage) {
	v.value = val
	v.isSet = true
}

func (v NullableHelmPackage) IsSet() bool {
	return v.isSet
}

func (v *NullableHelmPackage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHelmPackage(val *HelmPackage) *NullableHelmPackage {
	return &NullableHelmPackage{value: val, isSet: true}
}

func (v NullableHelmPackage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHelmPackage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


