/*
Omnistrate Fleet API

REST API for Omnistrate Fleet

API version: 2022-09-01-00
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fleet

import (
	"encoding/json"
	"fmt"
)

// checks if the UpdateCustomerOnboardingRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateCustomerOnboardingRequest{}

// UpdateCustomerOnboardingRequest struct for UpdateCustomerOnboardingRequest
type UpdateCustomerOnboardingRequest struct {
	// ID of a Customer Onboarding
	Id string `json:"id"`
	// The ID of the service associated with this onboarding.
	ServiceId *string `json:"serviceId,omitempty"`
	Stage *OnboardingStage `json:"stage,omitempty"`
	// JWT token used to perform authorization
	Token string `json:"token"`
	AdditionalProperties map[string]interface{}
}

type _UpdateCustomerOnboardingRequest UpdateCustomerOnboardingRequest

// NewUpdateCustomerOnboardingRequest instantiates a new UpdateCustomerOnboardingRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateCustomerOnboardingRequest(id string, token string) *UpdateCustomerOnboardingRequest {
	this := UpdateCustomerOnboardingRequest{}
	this.Id = id
	this.Token = token
	return &this
}

// NewUpdateCustomerOnboardingRequestWithDefaults instantiates a new UpdateCustomerOnboardingRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateCustomerOnboardingRequestWithDefaults() *UpdateCustomerOnboardingRequest {
	this := UpdateCustomerOnboardingRequest{}
	return &this
}

// GetId returns the Id field value
func (o *UpdateCustomerOnboardingRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UpdateCustomerOnboardingRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UpdateCustomerOnboardingRequest) SetId(v string) {
	o.Id = v
}

// GetServiceId returns the ServiceId field value if set, zero value otherwise.
func (o *UpdateCustomerOnboardingRequest) GetServiceId() string {
	if o == nil || IsNil(o.ServiceId) {
		var ret string
		return ret
	}
	return *o.ServiceId
}

// GetServiceIdOk returns a tuple with the ServiceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCustomerOnboardingRequest) GetServiceIdOk() (*string, bool) {
	if o == nil || IsNil(o.ServiceId) {
		return nil, false
	}
	return o.ServiceId, true
}

// HasServiceId returns a boolean if a field has been set.
func (o *UpdateCustomerOnboardingRequest) HasServiceId() bool {
	if o != nil && !IsNil(o.ServiceId) {
		return true
	}

	return false
}

// SetServiceId gets a reference to the given string and assigns it to the ServiceId field.
func (o *UpdateCustomerOnboardingRequest) SetServiceId(v string) {
	o.ServiceId = &v
}

// GetStage returns the Stage field value if set, zero value otherwise.
func (o *UpdateCustomerOnboardingRequest) GetStage() OnboardingStage {
	if o == nil || IsNil(o.Stage) {
		var ret OnboardingStage
		return ret
	}
	return *o.Stage
}

// GetStageOk returns a tuple with the Stage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCustomerOnboardingRequest) GetStageOk() (*OnboardingStage, bool) {
	if o == nil || IsNil(o.Stage) {
		return nil, false
	}
	return o.Stage, true
}

// HasStage returns a boolean if a field has been set.
func (o *UpdateCustomerOnboardingRequest) HasStage() bool {
	if o != nil && !IsNil(o.Stage) {
		return true
	}

	return false
}

// SetStage gets a reference to the given OnboardingStage and assigns it to the Stage field.
func (o *UpdateCustomerOnboardingRequest) SetStage(v OnboardingStage) {
	o.Stage = &v
}

// GetToken returns the Token field value
func (o *UpdateCustomerOnboardingRequest) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *UpdateCustomerOnboardingRequest) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *UpdateCustomerOnboardingRequest) SetToken(v string) {
	o.Token = v
}

func (o UpdateCustomerOnboardingRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateCustomerOnboardingRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.ServiceId) {
		toSerialize["serviceId"] = o.ServiceId
	}
	if !IsNil(o.Stage) {
		toSerialize["stage"] = o.Stage
	}
	toSerialize["token"] = o.Token

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateCustomerOnboardingRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateCustomerOnboardingRequest := _UpdateCustomerOnboardingRequest{}

	err = json.Unmarshal(data, &varUpdateCustomerOnboardingRequest)

	if err != nil {
		return err
	}

	*o = UpdateCustomerOnboardingRequest(varUpdateCustomerOnboardingRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "serviceId")
		delete(additionalProperties, "stage")
		delete(additionalProperties, "token")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateCustomerOnboardingRequest struct {
	value *UpdateCustomerOnboardingRequest
	isSet bool
}

func (v NullableUpdateCustomerOnboardingRequest) Get() *UpdateCustomerOnboardingRequest {
	return v.value
}

func (v *NullableUpdateCustomerOnboardingRequest) Set(val *UpdateCustomerOnboardingRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateCustomerOnboardingRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateCustomerOnboardingRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateCustomerOnboardingRequest(val *UpdateCustomerOnboardingRequest) *NullableUpdateCustomerOnboardingRequest {
	return &NullableUpdateCustomerOnboardingRequest{value: val, isSet: true}
}

func (v NullableUpdateCustomerOnboardingRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateCustomerOnboardingRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


