/*
Omnistrate Fleet API

REST API for Omnistrate Fleet

API version: 2022-09-01-00
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fleet

import (
	"encoding/json"
	"fmt"
)

// checks if the AdoptHostClusterRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdoptHostClusterRequest{}

// AdoptHostClusterRequest struct for AdoptHostClusterRequest
type AdoptHostClusterRequest struct {
	// ID of an CloudProvider
	CloudProviderId string `json:"cloudProviderId"`
	// Description of the host cluster
	Description string `json:"description"`
	// ID of a Host Cluster
	Id string `json:"id"`
	// ID of a Region
	RegionId string `json:"regionId"`
	// ID of a Subscription
	SubscriptionId *string `json:"subscriptionId,omitempty"`
	// JWT token used to perform authorization
	Token string `json:"token"`
	AdditionalProperties map[string]interface{}
}

type _AdoptHostClusterRequest AdoptHostClusterRequest

// NewAdoptHostClusterRequest instantiates a new AdoptHostClusterRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdoptHostClusterRequest(cloudProviderId string, description string, id string, regionId string, token string) *AdoptHostClusterRequest {
	this := AdoptHostClusterRequest{}
	this.CloudProviderId = cloudProviderId
	this.Description = description
	this.Id = id
	this.RegionId = regionId
	this.Token = token
	return &this
}

// NewAdoptHostClusterRequestWithDefaults instantiates a new AdoptHostClusterRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdoptHostClusterRequestWithDefaults() *AdoptHostClusterRequest {
	this := AdoptHostClusterRequest{}
	return &this
}

// GetCloudProviderId returns the CloudProviderId field value
func (o *AdoptHostClusterRequest) GetCloudProviderId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CloudProviderId
}

// GetCloudProviderIdOk returns a tuple with the CloudProviderId field value
// and a boolean to check if the value has been set.
func (o *AdoptHostClusterRequest) GetCloudProviderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CloudProviderId, true
}

// SetCloudProviderId sets field value
func (o *AdoptHostClusterRequest) SetCloudProviderId(v string) {
	o.CloudProviderId = v
}

// GetDescription returns the Description field value
func (o *AdoptHostClusterRequest) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *AdoptHostClusterRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *AdoptHostClusterRequest) SetDescription(v string) {
	o.Description = v
}

// GetId returns the Id field value
func (o *AdoptHostClusterRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AdoptHostClusterRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AdoptHostClusterRequest) SetId(v string) {
	o.Id = v
}

// GetRegionId returns the RegionId field value
func (o *AdoptHostClusterRequest) GetRegionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RegionId
}

// GetRegionIdOk returns a tuple with the RegionId field value
// and a boolean to check if the value has been set.
func (o *AdoptHostClusterRequest) GetRegionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RegionId, true
}

// SetRegionId sets field value
func (o *AdoptHostClusterRequest) SetRegionId(v string) {
	o.RegionId = v
}

// GetSubscriptionId returns the SubscriptionId field value if set, zero value otherwise.
func (o *AdoptHostClusterRequest) GetSubscriptionId() string {
	if o == nil || IsNil(o.SubscriptionId) {
		var ret string
		return ret
	}
	return *o.SubscriptionId
}

// GetSubscriptionIdOk returns a tuple with the SubscriptionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdoptHostClusterRequest) GetSubscriptionIdOk() (*string, bool) {
	if o == nil || IsNil(o.SubscriptionId) {
		return nil, false
	}
	return o.SubscriptionId, true
}

// HasSubscriptionId returns a boolean if a field has been set.
func (o *AdoptHostClusterRequest) HasSubscriptionId() bool {
	if o != nil && !IsNil(o.SubscriptionId) {
		return true
	}

	return false
}

// SetSubscriptionId gets a reference to the given string and assigns it to the SubscriptionId field.
func (o *AdoptHostClusterRequest) SetSubscriptionId(v string) {
	o.SubscriptionId = &v
}

// GetToken returns the Token field value
func (o *AdoptHostClusterRequest) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *AdoptHostClusterRequest) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *AdoptHostClusterRequest) SetToken(v string) {
	o.Token = v
}

func (o AdoptHostClusterRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdoptHostClusterRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cloudProviderId"] = o.CloudProviderId
	toSerialize["description"] = o.Description
	toSerialize["id"] = o.Id
	toSerialize["regionId"] = o.RegionId
	if !IsNil(o.SubscriptionId) {
		toSerialize["subscriptionId"] = o.SubscriptionId
	}
	toSerialize["token"] = o.Token

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AdoptHostClusterRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"cloudProviderId",
		"description",
		"id",
		"regionId",
		"token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAdoptHostClusterRequest := _AdoptHostClusterRequest{}

	err = json.Unmarshal(data, &varAdoptHostClusterRequest)

	if err != nil {
		return err
	}

	*o = AdoptHostClusterRequest(varAdoptHostClusterRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "cloudProviderId")
		delete(additionalProperties, "description")
		delete(additionalProperties, "id")
		delete(additionalProperties, "regionId")
		delete(additionalProperties, "subscriptionId")
		delete(additionalProperties, "token")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAdoptHostClusterRequest struct {
	value *AdoptHostClusterRequest
	isSet bool
}

func (v NullableAdoptHostClusterRequest) Get() *AdoptHostClusterRequest {
	return v.value
}

func (v *NullableAdoptHostClusterRequest) Set(val *AdoptHostClusterRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAdoptHostClusterRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAdoptHostClusterRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdoptHostClusterRequest(val *AdoptHostClusterRequest) *NullableAdoptHostClusterRequest {
	return &NullableAdoptHostClusterRequest{value: val, isSet: true}
}

func (v NullableAdoptHostClusterRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdoptHostClusterRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


