/*
Omnistrate Fleet API

REST API for Omnistrate Fleet

API version: 2022-09-01-00
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fleet

import (
	"encoding/json"
)

// checks if the InfrastructureAvailability type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InfrastructureAvailability{}

// InfrastructureAvailability struct for InfrastructureAvailability
type InfrastructureAvailability struct {
	ObservedAt *string `json:"observedAt,omitempty"`
	Reason *string `json:"reason,omitempty"`
	SourceAvailable *bool `json:"sourceAvailable,omitempty"`
	SourceUnavailableCode *string `json:"sourceUnavailableCode,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _InfrastructureAvailability InfrastructureAvailability

// NewInfrastructureAvailability instantiates a new InfrastructureAvailability object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInfrastructureAvailability() *InfrastructureAvailability {
	this := InfrastructureAvailability{}
	return &this
}

// NewInfrastructureAvailabilityWithDefaults instantiates a new InfrastructureAvailability object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInfrastructureAvailabilityWithDefaults() *InfrastructureAvailability {
	this := InfrastructureAvailability{}
	return &this
}

// GetObservedAt returns the ObservedAt field value if set, zero value otherwise.
func (o *InfrastructureAvailability) GetObservedAt() string {
	if o == nil || IsNil(o.ObservedAt) {
		var ret string
		return ret
	}
	return *o.ObservedAt
}

// GetObservedAtOk returns a tuple with the ObservedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InfrastructureAvailability) GetObservedAtOk() (*string, bool) {
	if o == nil || IsNil(o.ObservedAt) {
		return nil, false
	}
	return o.ObservedAt, true
}

// HasObservedAt returns a boolean if a field has been set.
func (o *InfrastructureAvailability) HasObservedAt() bool {
	if o != nil && !IsNil(o.ObservedAt) {
		return true
	}

	return false
}

// SetObservedAt gets a reference to the given string and assigns it to the ObservedAt field.
func (o *InfrastructureAvailability) SetObservedAt(v string) {
	o.ObservedAt = &v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *InfrastructureAvailability) GetReason() string {
	if o == nil || IsNil(o.Reason) {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InfrastructureAvailability) GetReasonOk() (*string, bool) {
	if o == nil || IsNil(o.Reason) {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *InfrastructureAvailability) HasReason() bool {
	if o != nil && !IsNil(o.Reason) {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *InfrastructureAvailability) SetReason(v string) {
	o.Reason = &v
}

// GetSourceAvailable returns the SourceAvailable field value if set, zero value otherwise.
func (o *InfrastructureAvailability) GetSourceAvailable() bool {
	if o == nil || IsNil(o.SourceAvailable) {
		var ret bool
		return ret
	}
	return *o.SourceAvailable
}

// GetSourceAvailableOk returns a tuple with the SourceAvailable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InfrastructureAvailability) GetSourceAvailableOk() (*bool, bool) {
	if o == nil || IsNil(o.SourceAvailable) {
		return nil, false
	}
	return o.SourceAvailable, true
}

// HasSourceAvailable returns a boolean if a field has been set.
func (o *InfrastructureAvailability) HasSourceAvailable() bool {
	if o != nil && !IsNil(o.SourceAvailable) {
		return true
	}

	return false
}

// SetSourceAvailable gets a reference to the given bool and assigns it to the SourceAvailable field.
func (o *InfrastructureAvailability) SetSourceAvailable(v bool) {
	o.SourceAvailable = &v
}

// GetSourceUnavailableCode returns the SourceUnavailableCode field value if set, zero value otherwise.
func (o *InfrastructureAvailability) GetSourceUnavailableCode() string {
	if o == nil || IsNil(o.SourceUnavailableCode) {
		var ret string
		return ret
	}
	return *o.SourceUnavailableCode
}

// GetSourceUnavailableCodeOk returns a tuple with the SourceUnavailableCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InfrastructureAvailability) GetSourceUnavailableCodeOk() (*string, bool) {
	if o == nil || IsNil(o.SourceUnavailableCode) {
		return nil, false
	}
	return o.SourceUnavailableCode, true
}

// HasSourceUnavailableCode returns a boolean if a field has been set.
func (o *InfrastructureAvailability) HasSourceUnavailableCode() bool {
	if o != nil && !IsNil(o.SourceUnavailableCode) {
		return true
	}

	return false
}

// SetSourceUnavailableCode gets a reference to the given string and assigns it to the SourceUnavailableCode field.
func (o *InfrastructureAvailability) SetSourceUnavailableCode(v string) {
	o.SourceUnavailableCode = &v
}

func (o InfrastructureAvailability) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InfrastructureAvailability) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ObservedAt) {
		toSerialize["observedAt"] = o.ObservedAt
	}
	if !IsNil(o.Reason) {
		toSerialize["reason"] = o.Reason
	}
	if !IsNil(o.SourceAvailable) {
		toSerialize["sourceAvailable"] = o.SourceAvailable
	}
	if !IsNil(o.SourceUnavailableCode) {
		toSerialize["sourceUnavailableCode"] = o.SourceUnavailableCode
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *InfrastructureAvailability) UnmarshalJSON(data []byte) (err error) {
	varInfrastructureAvailability := _InfrastructureAvailability{}

	err = json.Unmarshal(data, &varInfrastructureAvailability)

	if err != nil {
		return err
	}

	*o = InfrastructureAvailability(varInfrastructureAvailability)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "observedAt")
		delete(additionalProperties, "reason")
		delete(additionalProperties, "sourceAvailable")
		delete(additionalProperties, "sourceUnavailableCode")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableInfrastructureAvailability struct {
	value *InfrastructureAvailability
	isSet bool
}

func (v NullableInfrastructureAvailability) Get() *InfrastructureAvailability {
	return v.value
}

func (v *NullableInfrastructureAvailability) Set(val *InfrastructureAvailability) {
	v.value = val
	v.isSet = true
}

func (v NullableInfrastructureAvailability) IsSet() bool {
	return v.isSet
}

func (v *NullableInfrastructureAvailability) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInfrastructureAvailability(val *InfrastructureAvailability) *NullableInfrastructureAvailability {
	return &NullableInfrastructureAvailability{value: val, isSet: true}
}

func (v NullableInfrastructureAvailability) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInfrastructureAvailability) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


