/*
Omnistrate Fleet API

REST API for Omnistrate Fleet

API version: 2022-09-01-00
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fleet

import (
	"encoding/json"
	"fmt"
)

// checks if the DeploymentCellAmenityArtifactSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeploymentCellAmenityArtifactSummary{}

// DeploymentCellAmenityArtifactSummary struct for DeploymentCellAmenityArtifactSummary
type DeploymentCellAmenityArtifactSummary struct {
	// The amenity name
	AmenityName string `json:"amenityName"`
	// The artifact kind
	ArtifactKind string `json:"artifactKind"`
	// The artifact payload encoding
	ContentEncoding *string `json:"contentEncoding,omitempty"`
	// The artifact content type
	ContentType *string `json:"contentType,omitempty"`
	// The amenity generation for this artifact
	Generation int64 `json:"generation"`
	// Base64-encoded uncompressed artifact payload for debug views
	PayloadBase64 *string `json:"payloadBase64,omitempty"`
	// Whether secrets have been masked in this artifact
	SecretMasked *bool `json:"secretMasked,omitempty"`
	// The SHA256 hash of the uncompressed artifact payload
	Sha256 *string `json:"sha256,omitempty"`
	// The uncompressed artifact size
	SizeBytes *int64 `json:"sizeBytes,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DeploymentCellAmenityArtifactSummary DeploymentCellAmenityArtifactSummary

// NewDeploymentCellAmenityArtifactSummary instantiates a new DeploymentCellAmenityArtifactSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeploymentCellAmenityArtifactSummary(amenityName string, artifactKind string, generation int64) *DeploymentCellAmenityArtifactSummary {
	this := DeploymentCellAmenityArtifactSummary{}
	this.AmenityName = amenityName
	this.ArtifactKind = artifactKind
	this.Generation = generation
	return &this
}

// NewDeploymentCellAmenityArtifactSummaryWithDefaults instantiates a new DeploymentCellAmenityArtifactSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeploymentCellAmenityArtifactSummaryWithDefaults() *DeploymentCellAmenityArtifactSummary {
	this := DeploymentCellAmenityArtifactSummary{}
	return &this
}

// GetAmenityName returns the AmenityName field value
func (o *DeploymentCellAmenityArtifactSummary) GetAmenityName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AmenityName
}

// GetAmenityNameOk returns a tuple with the AmenityName field value
// and a boolean to check if the value has been set.
func (o *DeploymentCellAmenityArtifactSummary) GetAmenityNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AmenityName, true
}

// SetAmenityName sets field value
func (o *DeploymentCellAmenityArtifactSummary) SetAmenityName(v string) {
	o.AmenityName = v
}

// GetArtifactKind returns the ArtifactKind field value
func (o *DeploymentCellAmenityArtifactSummary) GetArtifactKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ArtifactKind
}

// GetArtifactKindOk returns a tuple with the ArtifactKind field value
// and a boolean to check if the value has been set.
func (o *DeploymentCellAmenityArtifactSummary) GetArtifactKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ArtifactKind, true
}

// SetArtifactKind sets field value
func (o *DeploymentCellAmenityArtifactSummary) SetArtifactKind(v string) {
	o.ArtifactKind = v
}

// GetContentEncoding returns the ContentEncoding field value if set, zero value otherwise.
func (o *DeploymentCellAmenityArtifactSummary) GetContentEncoding() string {
	if o == nil || IsNil(o.ContentEncoding) {
		var ret string
		return ret
	}
	return *o.ContentEncoding
}

// GetContentEncodingOk returns a tuple with the ContentEncoding field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentCellAmenityArtifactSummary) GetContentEncodingOk() (*string, bool) {
	if o == nil || IsNil(o.ContentEncoding) {
		return nil, false
	}
	return o.ContentEncoding, true
}

// HasContentEncoding returns a boolean if a field has been set.
func (o *DeploymentCellAmenityArtifactSummary) HasContentEncoding() bool {
	if o != nil && !IsNil(o.ContentEncoding) {
		return true
	}

	return false
}

// SetContentEncoding gets a reference to the given string and assigns it to the ContentEncoding field.
func (o *DeploymentCellAmenityArtifactSummary) SetContentEncoding(v string) {
	o.ContentEncoding = &v
}

// GetContentType returns the ContentType field value if set, zero value otherwise.
func (o *DeploymentCellAmenityArtifactSummary) GetContentType() string {
	if o == nil || IsNil(o.ContentType) {
		var ret string
		return ret
	}
	return *o.ContentType
}

// GetContentTypeOk returns a tuple with the ContentType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentCellAmenityArtifactSummary) GetContentTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ContentType) {
		return nil, false
	}
	return o.ContentType, true
}

// HasContentType returns a boolean if a field has been set.
func (o *DeploymentCellAmenityArtifactSummary) HasContentType() bool {
	if o != nil && !IsNil(o.ContentType) {
		return true
	}

	return false
}

// SetContentType gets a reference to the given string and assigns it to the ContentType field.
func (o *DeploymentCellAmenityArtifactSummary) SetContentType(v string) {
	o.ContentType = &v
}

// GetGeneration returns the Generation field value
func (o *DeploymentCellAmenityArtifactSummary) GetGeneration() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Generation
}

// GetGenerationOk returns a tuple with the Generation field value
// and a boolean to check if the value has been set.
func (o *DeploymentCellAmenityArtifactSummary) GetGenerationOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Generation, true
}

// SetGeneration sets field value
func (o *DeploymentCellAmenityArtifactSummary) SetGeneration(v int64) {
	o.Generation = v
}

// GetPayloadBase64 returns the PayloadBase64 field value if set, zero value otherwise.
func (o *DeploymentCellAmenityArtifactSummary) GetPayloadBase64() string {
	if o == nil || IsNil(o.PayloadBase64) {
		var ret string
		return ret
	}
	return *o.PayloadBase64
}

// GetPayloadBase64Ok returns a tuple with the PayloadBase64 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentCellAmenityArtifactSummary) GetPayloadBase64Ok() (*string, bool) {
	if o == nil || IsNil(o.PayloadBase64) {
		return nil, false
	}
	return o.PayloadBase64, true
}

// HasPayloadBase64 returns a boolean if a field has been set.
func (o *DeploymentCellAmenityArtifactSummary) HasPayloadBase64() bool {
	if o != nil && !IsNil(o.PayloadBase64) {
		return true
	}

	return false
}

// SetPayloadBase64 gets a reference to the given string and assigns it to the PayloadBase64 field.
func (o *DeploymentCellAmenityArtifactSummary) SetPayloadBase64(v string) {
	o.PayloadBase64 = &v
}

// GetSecretMasked returns the SecretMasked field value if set, zero value otherwise.
func (o *DeploymentCellAmenityArtifactSummary) GetSecretMasked() bool {
	if o == nil || IsNil(o.SecretMasked) {
		var ret bool
		return ret
	}
	return *o.SecretMasked
}

// GetSecretMaskedOk returns a tuple with the SecretMasked field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentCellAmenityArtifactSummary) GetSecretMaskedOk() (*bool, bool) {
	if o == nil || IsNil(o.SecretMasked) {
		return nil, false
	}
	return o.SecretMasked, true
}

// HasSecretMasked returns a boolean if a field has been set.
func (o *DeploymentCellAmenityArtifactSummary) HasSecretMasked() bool {
	if o != nil && !IsNil(o.SecretMasked) {
		return true
	}

	return false
}

// SetSecretMasked gets a reference to the given bool and assigns it to the SecretMasked field.
func (o *DeploymentCellAmenityArtifactSummary) SetSecretMasked(v bool) {
	o.SecretMasked = &v
}

// GetSha256 returns the Sha256 field value if set, zero value otherwise.
func (o *DeploymentCellAmenityArtifactSummary) GetSha256() string {
	if o == nil || IsNil(o.Sha256) {
		var ret string
		return ret
	}
	return *o.Sha256
}

// GetSha256Ok returns a tuple with the Sha256 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentCellAmenityArtifactSummary) GetSha256Ok() (*string, bool) {
	if o == nil || IsNil(o.Sha256) {
		return nil, false
	}
	return o.Sha256, true
}

// HasSha256 returns a boolean if a field has been set.
func (o *DeploymentCellAmenityArtifactSummary) HasSha256() bool {
	if o != nil && !IsNil(o.Sha256) {
		return true
	}

	return false
}

// SetSha256 gets a reference to the given string and assigns it to the Sha256 field.
func (o *DeploymentCellAmenityArtifactSummary) SetSha256(v string) {
	o.Sha256 = &v
}

// GetSizeBytes returns the SizeBytes field value if set, zero value otherwise.
func (o *DeploymentCellAmenityArtifactSummary) GetSizeBytes() int64 {
	if o == nil || IsNil(o.SizeBytes) {
		var ret int64
		return ret
	}
	return *o.SizeBytes
}

// GetSizeBytesOk returns a tuple with the SizeBytes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeploymentCellAmenityArtifactSummary) GetSizeBytesOk() (*int64, bool) {
	if o == nil || IsNil(o.SizeBytes) {
		return nil, false
	}
	return o.SizeBytes, true
}

// HasSizeBytes returns a boolean if a field has been set.
func (o *DeploymentCellAmenityArtifactSummary) HasSizeBytes() bool {
	if o != nil && !IsNil(o.SizeBytes) {
		return true
	}

	return false
}

// SetSizeBytes gets a reference to the given int64 and assigns it to the SizeBytes field.
func (o *DeploymentCellAmenityArtifactSummary) SetSizeBytes(v int64) {
	o.SizeBytes = &v
}

func (o DeploymentCellAmenityArtifactSummary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeploymentCellAmenityArtifactSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["amenityName"] = o.AmenityName
	toSerialize["artifactKind"] = o.ArtifactKind
	if !IsNil(o.ContentEncoding) {
		toSerialize["contentEncoding"] = o.ContentEncoding
	}
	if !IsNil(o.ContentType) {
		toSerialize["contentType"] = o.ContentType
	}
	toSerialize["generation"] = o.Generation
	if !IsNil(o.PayloadBase64) {
		toSerialize["payloadBase64"] = o.PayloadBase64
	}
	if !IsNil(o.SecretMasked) {
		toSerialize["secretMasked"] = o.SecretMasked
	}
	if !IsNil(o.Sha256) {
		toSerialize["sha256"] = o.Sha256
	}
	if !IsNil(o.SizeBytes) {
		toSerialize["sizeBytes"] = o.SizeBytes
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DeploymentCellAmenityArtifactSummary) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"amenityName",
		"artifactKind",
		"generation",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeploymentCellAmenityArtifactSummary := _DeploymentCellAmenityArtifactSummary{}

	err = json.Unmarshal(data, &varDeploymentCellAmenityArtifactSummary)

	if err != nil {
		return err
	}

	*o = DeploymentCellAmenityArtifactSummary(varDeploymentCellAmenityArtifactSummary)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "amenityName")
		delete(additionalProperties, "artifactKind")
		delete(additionalProperties, "contentEncoding")
		delete(additionalProperties, "contentType")
		delete(additionalProperties, "generation")
		delete(additionalProperties, "payloadBase64")
		delete(additionalProperties, "secretMasked")
		delete(additionalProperties, "sha256")
		delete(additionalProperties, "sizeBytes")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDeploymentCellAmenityArtifactSummary struct {
	value *DeploymentCellAmenityArtifactSummary
	isSet bool
}

func (v NullableDeploymentCellAmenityArtifactSummary) Get() *DeploymentCellAmenityArtifactSummary {
	return v.value
}

func (v *NullableDeploymentCellAmenityArtifactSummary) Set(val *DeploymentCellAmenityArtifactSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableDeploymentCellAmenityArtifactSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableDeploymentCellAmenityArtifactSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeploymentCellAmenityArtifactSummary(val *DeploymentCellAmenityArtifactSummary) *NullableDeploymentCellAmenityArtifactSummary {
	return &NullableDeploymentCellAmenityArtifactSummary{value: val, isSet: true}
}

func (v NullableDeploymentCellAmenityArtifactSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeploymentCellAmenityArtifactSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


