/*
Omnistrate Registration API

Testing ConsumptionPaymentMethodApiAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package v1

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/omnistrate-oss/omnistrate-sdk-go/v1"
)

func Test_v1_ConsumptionPaymentMethodApiAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ConsumptionPaymentMethodApiAPIService ConsumptionPaymentMethodApiCreateConsumptionSetupIntent", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ConsumptionPaymentMethodApiAPI.ConsumptionPaymentMethodApiCreateConsumptionSetupIntent(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ConsumptionPaymentMethodApiAPIService ConsumptionPaymentMethodApiGetConsumptionStripeConfig", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ConsumptionPaymentMethodApiAPI.ConsumptionPaymentMethodApiGetConsumptionStripeConfig(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ConsumptionPaymentMethodApiAPIService ConsumptionPaymentMethodApiListConsumptionPaymentMethods", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ConsumptionPaymentMethodApiAPI.ConsumptionPaymentMethodApiListConsumptionPaymentMethods(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ConsumptionPaymentMethodApiAPIService ConsumptionPaymentMethodApiRemoveConsumptionPaymentMethod", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		httpRes, err := apiClient.ConsumptionPaymentMethodApiAPI.ConsumptionPaymentMethodApiRemoveConsumptionPaymentMethod(context.Background(), id).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ConsumptionPaymentMethodApiAPIService ConsumptionPaymentMethodApiSetDefaultConsumptionPaymentMethod", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		httpRes, err := apiClient.ConsumptionPaymentMethodApiAPI.ConsumptionPaymentMethodApiSetDefaultConsumptionPaymentMethod(context.Background(), id).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
