name: SDK Update

on:
  workflow_dispatch:
    inputs:
      branch-prefix:
        description: 'Branch name prefix'
        required: true
        default: 'sdk-update'
  pull_request:
    branches: [ "main" ] 
    
env:  
  GOMAXPROCS: 2

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
  
jobs:
  update-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Set branch name
        run: echo "BRANCH_NAME=${{ github.event.inputs.branch-prefix }}-$(date +%Y%m%d-%H%M%S)" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5
        with:
          go-version-file: 'go.mod'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a
        with:
          node-version: '20'

      - name: Install openapi-generator-cli
        run: npm install @openapitools/openapi-generator-cli -g

      - name: Run make to update SDK and docs
        run: make
        
      - name: Create branch and commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout -b ${{ env.BRANCH_NAME }}
          git add .
          git commit -m "chore: update SDK"
          git push origin ${{ env.BRANCH_NAME }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e
        with:
          title: 'chore: SDK Update'
          body: 'Automated SDK update via GitHub Actions'
          branch: ${{ env.BRANCH_NAME }}
          base: main
          labels: |
            automated-pr
            sdk-update
