name: Update SDK

on:
  workflow_dispatch:
    
env:  
  GOMAXPROCS: 2

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
              
      - name: Set up go
        timeout-minutes: 10
        uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5
        with:
          go-version-file: 'go.mod'
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Get dependencies
        timeout-minutes: 10
        run: | 
          make download

      - name: Build
        timeout-minutes: 10
        run: make build

      - name: Create PR
        uses: peter-evans/create-pull-request@67ccf781d68cd99b580ae25a5c18a1cc84ffff1f
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update SDK'
          title: 'chore: update SDK'
          body: 'This PR updates the SDK to the latest API version.'
          branch-suffix: update-sdk
          committer: 'GH Automation <noreply@omnistrate.com>'
        
        